(function(){
'use strict';
var CATS={
 'Depreciação':'fixo','Remuneração do capital':'fixo','Financiamento / Leasing':'fixo','Seguro':'fixo','IPVA / Licenciamento':'fixo','Rastreamento / Telemetria':'fixo','Garagem / Estacionamento':'fixo','Documentação / Taxas':'fixo',
 'Salário':'fixo','Encargos patronais':'fixo','FGTS':'fixo','13º salário':'fixo','Férias + 1/3':'fixo','Benefícios':'fixo',
 'Combustível':'variavel','ARLA 32':'variavel','Pedágio':'variavel','Estacionamento em viagem':'variavel','Pneus / Recapagem':'variavel','Manutenção preventiva':'variavel','Manutenção corretiva':'variavel','Peças':'variavel','Lubrificantes / Filtros':'variavel','Lavagem':'variavel','Multas':'variavel','Diárias / Adicionais':'variavel','Custos administrativos':'indireto','Outros custos fixos':'fixo','Outros custos variáveis':'variavel'
};
var estado={chart:null,tab:'lancamentos',paginaLancamentos:1,paginaRecorrentes:1,paginaKm:1,paginaVeiculos:1,itensPagina:15};
function arr(k){return typeof db!=='undefined'&&Array.isArray(db[k])?db[k]:[]}
function uid(p){return (p||'id')+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,9)}
function num(v){if(typeof v==='number')return isFinite(v)?v:0;if(typeof moedaParaFloat==='function')return moedaParaFloat(v);return Number(String(v||0).replace(/R\$\s?/g,'').replace(/\./g,'').replace(',','.'))||0}
function brl(v){return (Number(v)||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function data(v){if(!v)return '';var s=String(v).trim();if(/^\d{4}-\d{2}-\d{2}/.test(s))return s.slice(0,10);var p=s.match(/(\d{2})[\/.-](\d{2})[\/.-](\d{2,4})/);if(!p)return '';return (p[3].length===2?'20'+p[3]:p[3])+'-'+p[2]+'-'+p[1]}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function hoje(){return new Date().toISOString().slice(0,10)}
function mesInicio(d){var x=d?new Date(d+'T12:00:00'):new Date();return x.getFullYear()+'-'+String(x.getMonth()+1).padStart(2,'0')+'-01'}
function mesFim(d){var x=d?new Date(d+'T12:00:00'):new Date();return new Date(x.getFullYear(),x.getMonth()+1,0).toISOString().slice(0,10)}
function val(id){var e=document.getElementById(id);return e?e.value:''}
function set(id,v){var e=document.getElementById(id);if(e)e.textContent=v}
function mesChave(d){return data(d).slice(0,7)}
function veiculoMotorista(placa){var v=arr('veiculos').find(function(x){return x.vplaca===placa});return v&&v.vmotorista||''}
function normalizarPlaca(v){return String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'')}
function hashRegistro(x){return [normalizarPlaca(x.veiculo),data(x.data),x.categoria,Number(x.valor||0).toFixed(2)].join('|')}
function origem(lista,mod,cat,tipo,placaCampo,dataCampo,valorFn,descFn){arr(mod).forEach(function(x,i){var valor=valorFn(x),dt=data(x[dataCampo]);if(valor<=0||!dt)return;lista.push({id:'auto-'+mod+'-'+(x.id||i),automatico:true,origem:mod,categoria:cat,tipo:tipo,veiculo:x[placaCampo]||'',motorista:veiculoMotorista(x[placaCampo]),data:dt,competencia:dt.slice(0,7),descricao:descFn(x),valor:valor,status:'Realizado'})})}
function origemAnual(lista,mod,cat,placaCampo,dataCampo,valorCampo,descricao){arr(mod).forEach(function(x,i){var total=num(x[valorCampo]),dt=data(x[dataCampo]);if(total<=0||!dt)return;for(var m=1;m<=12;m++){var ds=dt.slice(0,4)+'-'+String(m).padStart(2,'0')+'-01';lista.push({id:'auto-'+mod+'-'+(x.id||i)+'-'+m,automatico:true,origem:mod,categoria:cat,tipo:'fixo',veiculo:x[placaCampo]||'',motorista:veiculoMotorista(x[placaCampo]),data:ds,competencia:ds.slice(0,7),descricao:'Apropriação mensal — '+descricao,valor:total/12,status:'Provisionado',periodicidade:'anual'})}})}
function automaticos(){return []}
function recorrentes(inicio,fim){var out=[];arr('custosRecorrentes').forEach(function(r,ri){if(r.ativo===false)return;var start=data(r.inicio)||inicio,end=data(r.fim)||fim,ini=new Date(start+'T12:00:00'),limI=new Date(inicio+'T12:00:00'),limF=new Date(fim+'T12:00:00'),limEnd=new Date(end+'T12:00:00');if(ini<limI)ini=limI;var cur=new Date(ini.getFullYear(),ini.getMonth(),1),valor=r.periodicidade==='anual'?num(r.valor)/12:num(r.valor);while(cur<=limF&&cur<=limEnd){var ds=cur.getFullYear()+'-'+String(cur.getMonth()+1).padStart(2,'0')+'-01';out.push({id:'rec-'+(r.id||ri)+'-'+ds,automatico:true,projecaoRecorrente:true,origem:r.origem||'recorrente',categoria:r.categoria,tipo:r.tipo||CATS[r.categoria]||'fixo',veiculo:r.veiculo||'',motorista:r.motorista||'',data:ds,competencia:ds.slice(0,7),descricao:r.descricao||r.categoria,valor:valor,status:'Provisionado',rateio:r.rateio||'nao',periodicidade:r.periodicidade||'mensal'});cur=new Date(cur.getFullYear(),cur.getMonth()+1,1)}});return out}
function filtros(){return {v:val('cusFiltroVeiculo'),ini:val('cusFiltroInicio')||mesInicio(),fim:val('cusFiltroFim')||mesFim(),tipo:val('cusFiltroTipo'),cat:val('cusFiltroCategoria'),origem:val('cusFiltroOrigem'),status:val('cusFiltroStatus')}}
function migrarIds(){var mudou=[];['custos','custosRecorrentes','quilometragens','importacoesPedagio'].forEach(function(k){arr(k).forEach(function(x){if(!x.id){x.id=uid(k);if(mudou.indexOf(k)<0)mudou.push(k)}})});if(mudou.length&&typeof salvarNuvem==='function')salvarNuvem(mudou)}
function todosBase(){var f=filtros();return arr('custos').map(function(x){var item=Object.assign({automatico:false,origem:'manual'},x,{valor:num(x.valor),data:data(x.data),id:x.id||uid('cus')});if(item.origem==='pedagio_importado'&&Array.isArray(item.detalhesPedagio)){var ds=item.detalhesPedagio.filter(function(d){var dt=data(d.data);return (!f.ini||dt>=f.ini)&&(!f.fim||dt<=f.fim)});item.valor=ds.reduce(function(t,d){return t+num(d.valor)},0);if(!ds.length)item.valor=0}return item}).filter(function(x){return x.origem!=='pedagio_importado'||x.valor>0}).concat(recorrentes(f.ini,f.fim))}
function kmPeriodo(placa,ini,fim){return arr('quilometragens').filter(function(x){return (!placa||x.veiculo===placa)&&data(x.data)>=ini&&data(x.data)<=fim}).reduce(function(s,x){return s+Math.max(0,num(x.kmRodado)||(num(x.odometroFinal)-num(x.odometroInicial)))},0)}
function faturamentoPeriodo(placa,ini,fim){return arr('producoes').filter(function(x){if(x.statusOperacional==='Cancelada'||(placa&&x.veiculo!==placa))return false;var competencia=x.competencia||mesChave(x.dataFim||x.dataInicio),dt=competencia?competencia+'-01':data(x.dataFim||x.dataInicio);return !!dt&&dt>=mesInicio(ini)&&dt<=mesFim(fim)}).reduce(function(s,x){return s+num(x.receitaBruta)},0)}
function receitaLiquidaPeriodo(placa,ini,fim){return arr('producoes').filter(function(x){if(x.statusOperacional==='Cancelada'||(placa&&x.veiculo!==placa))return false;var competencia=x.competencia||mesChave(x.dataFim||x.dataInicio),dt=competencia?competencia+'-01':data(x.dataFim||x.dataInicio);return !!dt&&dt>=mesInicio(ini)&&dt<=mesFim(fim)}).reduce(function(s,x){return s+num(x.receitaBruta)-num(x.descontos)-num(x.impostos)+num(x.ajuste)},0)}
function ratearParaVeiculo(x,placa,f){if(x.veiculo)return x.veiculo===placa?x:null;if(x.rateio==='igual'){var vs=veiculosGestao();return vs.indexOf(placa)>=0?Object.assign({},x,{veiculo:placa,valor:x.valor/vs.length,rateado:true}):null}if(x.rateio==='km'){var total=kmPeriodo('',f.ini,f.fim),km=kmPeriodo(placa,f.ini,f.fim);return total&&km?Object.assign({},x,{veiculo:placa,valor:x.valor*km/total,rateado:true}):null}return null}
function filtrados(placaForcada,filtroForcado){var f=filtroForcado||filtros(),placa=placaForcada===undefined?f.v:placaForcada,l=todosBase();if(placa)l=l.map(function(x){return ratearParaVeiculo(x,placa,f)}).filter(Boolean);return l.filter(function(x){var comp=(x.competencia||mesChave(x.data)),di=comp?comp+'-01':data(x.data);return (!f.ini||di>=mesInicio(f.ini))&&(!f.fim||di<=mesFim(f.fim))&&(!f.tipo||x.tipo===f.tipo)&&(!f.cat||x.categoria===f.cat)&&(!f.origem||x.origem===f.origem)&&(!f.status||x.status===f.status)}).sort(function(a,b){return (b.competencia||b.data||'').localeCompare(a.competencia||a.data||'')})}
function preencherSelects(){var vs=arr('veiculos'),ativos=vs.filter(function(v){return String(v.vstatus||'').toUpperCase()!=='VENDIDO'}),opts='<option value="">Todos os veículos</option>'+vs.map(function(v){return '<option value="'+esc(v.vplaca)+'">'+esc(v.vplaca)+' — '+esc(v.vmodelo||'')+'</option>'}).join(''),f=document.getElementById('cusFiltroVeiculo'),old=f&&f.value;if(f){f.innerHTML=opts;f.value=old||''}var dl=document.getElementById('cusVeiculosLista');if(dl)dl.innerHTML=ativos.map(function(v){return '<option value="'+esc(v.vplaca)+'">'+esc(v.vmodelo||'')+'</option>'}).join('');var ml=document.getElementById('cusMotoristasLista');if(ml)ml.innerHTML=arr('motoristas').filter(function(m){return String(m.motStatus||'ATIVO').toUpperCase()!=='INATIVO'}).map(function(m){var nome=m.motNome||m.mnome||m.nome||'';return '<option value="'+esc(nome)+'"></option>'}).join('');var pl=document.getElementById('cusPneusLista');if(pl)pl.innerHTML=arr('pneus').map(function(p){return '<option value="'+esc(p.pnumero||p.pid||'')+'"></option>'}).join('')}
function render(){if(!document.getElementById('custos'))return;preencherSelects();var l=filtrados(),f=filtros(),total=l.reduce(function(s,x){return s+x.valor},0),faturamento=faturamentoPeriodo(f.v,f.ini,f.fim),fix=l.filter(function(x){return x.tipo==='fixo'}).reduce(function(s,x){return s+x.valor},0),ind=l.filter(function(x){return x.tipo==='indireto'}).reduce(function(s,x){return s+x.valor},0),vari=total-fix-ind,km=kmPeriodo(f.v,f.ini,f.fim);set('cusTotal',brl(total));set('cusFaturamento',brl(faturamento));set('cusFixo',brl(fix));set('cusVariavel',brl(vari));set('cusKm',km.toLocaleString('pt-BR')+' km');set('cusCustoKm',km?brl(total/km):'Sem leitura');set('cusPeriodoLabel',f.ini.slice(0,7)===f.fim.slice(0,7)?'Competência '+f.ini.slice(0,7).split('-').reverse().join('/'):'Período selecionado');var alerta=document.getElementById('cusKmAlerta');if(alerta)alerta.textContent=km?'':'Falta quilometragem no período.';renderTabela(l);renderCategorias(l,total);renderVeiculos(f);renderRecorrentes();renderKm();renderPendencias(l,f,km);grafico(l)}
function renderPendencias(l,f,km){var msgs=[];if(!km)msgs.push('quilometragem ausente');var semVeiculo=l.filter(function(x){return !x.veiculo&&x.rateio==='nao'}).length;if(semVeiculo)msgs.push(semVeiculo+' custo(s) sem veículo ou rateio');var rec=arr('custosRecorrentes').filter(function(x){return x.periodicidade==='anual'&&!x.inicio}).length;if(rec)msgs.push(rec+' custo(s) anual(is) sem vigência');var el=document.getElementById('cusPendencias');if(!el)return;el.classList.toggle('show',!!msgs.length);el.textContent=msgs.length?'Pendências para um cálculo completo: '+msgs.join(' • '):''}
function tipoBadge(x){return x.tipo==='fixo'?'fix':x.tipo==='indireto'?'ind':'var'}
function paginar(lista,chave){var paginas=Math.max(1,Math.ceil(lista.length/estado.itensPagina));estado[chave]=Math.min(Math.max(1,estado[chave]||1),paginas);var ini=(estado[chave]-1)*estado.itensPagina,fn="mudarPaginaGestao('"+chave+"',";return {itens:lista.slice(ini,ini+estado.itensPagina),html:lista.length>estado.itensPagina?'<div class="paginacao-global"><button '+(estado[chave]===1?'disabled':'')+' onclick="'+fn+'1)">&lt;&lt; Primeira</button><button '+(estado[chave]===1?'disabled':'')+' onclick="'+fn+(estado[chave]-1)+')">&lt; Anterior</button><div class="pagina-info">Página '+estado[chave]+' de '+paginas+'</div><button '+(estado[chave]===paginas?'disabled':'')+' onclick="'+fn+(estado[chave]+1)+')">Próxima &gt;</button><button '+(estado[chave]===paginas?'disabled':'')+' onclick="'+fn+paginas+')">Última &gt;&gt;</button></div>':''}}
function renderTabela(l){var tb=document.getElementById('cusLista');if(!tb)return;var p=paginar(l,'paginaLancamentos');tb.innerHTML=p.itens.length?p.itens.map(function(x){var acao=x.projecaoRecorrente?'<span class="cus-mini">projeção</span>':'<button class="btn-edit" onclick="editarCustoFrota(\''+esc(x.id)+'\')">✎ Editar</button><button class="btn-del" onclick="excluirCustoFrota(\''+esc(x.id)+'\')">✕ Excluir</button>';return '<tr><td>'+esc(x.data?x.data.split('-').reverse().join('/'):'--')+'</td><td>'+esc(x.competencia||'--')+'</td><td><b>'+esc(x.veiculo||'Frota geral')+'</b></td><td>'+esc(x.categoria)+'</td><td>'+esc(x.descricao||'--')+(x.rateado?'<span class="cus-source-note">valor rateado</span>':'')+'</td><td><span class="cus-badge '+tipoBadge(x)+'">'+(x.tipo==='fixo'?'Fixo':x.tipo==='indireto'?'Indireto':'Variável')+'</span></td><td><span class="cus-badge manual">'+esc(x.origem==='pedagio_importado'?'Pedágio mensal':x.origem)+'</span></td><td>'+esc(x.status||'Realizado')+'</td><td><b>'+brl(x.valor)+'</b></td><td class="cus-history-actions">'+acao+'</td></tr>'}).join(''):'<tr><td colspan="10" class="cus-empty">Nenhum custo encontrado neste período.</td></tr>';var pg=document.getElementById('cusListaPaginacao');if(pg)pg.innerHTML=p.html}
function renderCategorias(l,total){var m={};l.forEach(function(x){m[x.categoria]=(m[x.categoria]||0)+x.valor});var el=document.getElementById('cusCategorias');if(!el)return;el.innerHTML=Object.keys(m).sort(function(a,b){return m[b]-m[a]}).slice(0,10).map(function(k){var p=total?m[k]/total*100:0;return '<div class="mb-3"><div class="d-flex justify-content-between"><b>'+esc(k)+'</b><span>'+brl(m[k])+' · '+p.toFixed(1).replace('.',',')+'%</span></div><div class="cus-progress"><i style="width:'+Math.min(100,p)+'%"></i></div></div>'}).join('')||'<div class="cus-empty">Sem dados no período.</div>'}
function renderVeiculos(f){var placas=f.v?[f.v]:veiculosGestao(),linhas=[];placas.forEach(function(pl){var l=filtrados(pl),fix=0,vari=0,ind=0;l.forEach(function(x){if(x.tipo==='fixo')fix+=x.valor;else if(x.tipo==='indireto')ind+=x.valor;else vari+=x.valor});var total=fix+vari+ind,km=kmPeriodo(pl,f.ini,f.fim),faturamento=faturamentoPeriodo(pl,f.ini,f.fim),receitaLiquida=receitaLiquidaPeriodo(pl,f.ini,f.fim);if(total||km||faturamento||receitaLiquida)linhas.push({placa:pl,faturamento:faturamento,receitaLiquida:receitaLiquida,fix:fix,vari:vari,ind:ind,total:total,km:km})});var el=document.getElementById('cusPorVeiculo'),p=paginar(linhas,'paginaVeiculos');if(el)el.innerHTML=p.itens.map(function(x){return '<tr><td><b>'+esc(x.placa)+'</b></td><td><b>'+brl(x.faturamento)+'</b></td><td><b>'+brl(x.receitaLiquida)+'</b></td><td>'+brl(x.fix)+'</td><td>'+brl(x.vari)+'</td><td>'+brl(x.ind)+'</td><td><b>'+brl(x.total)+'</b></td><td>'+x.km.toLocaleString('pt-BR')+' km</td><td><b>'+(x.km?brl(x.total/x.km):'--')+'</b></td></tr>'}).join('')||'<tr><td colspan="9" class="cus-empty">Sem dados por veículo.</td></tr>';var pg=document.getElementById('cusVeiculosPaginacao');if(pg)pg.innerHTML=p.html}
function grafico(l){var el=document.getElementById('cusGrafico');if(!el||typeof Chart==='undefined')return;var m={};l.forEach(function(x){m[x.categoria]=(m[x.categoria]||0)+x.valor});var ks=Object.keys(m).sort(function(a,b){return m[b]-m[a]}).slice(0,8);if(estado.chart)estado.chart.destroy();estado.chart=new Chart(el,{type:'doughnut',data:{labels:ks,datasets:[{data:ks.map(function(k){return m[k]}),backgroundColor:['#2563eb','#0f766e','#f59e0b','#dc2626','#7c3aed','#0891b2','#64748b','#db2777'],borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom'}}}})}
function salvarCusto(){var id=val('cusIdx'),cat=val('cusCategoria'),valor=num(val('cusValor')),dt=val('cusData');if(!dt||!cat||valor<=0){alert('Informe data, categoria e um valor maior que zero.');return}var obj={id:id||uid('cus'),data:dt,competencia:val('cusCompetencia')||dt.slice(0,7),veiculo:val('cusVeiculo'),motorista:val('cusMotorista'),categoria:cat,tipo:val('cusTipo')||CATS[cat]||'variavel',descricao:val('cusDescricao'),valor:valor,status:val('cusStatus'),rateio:val('cusRateio'),observacao:val('cusObservacao'),origem:'manual',atualizadoEm:new Date().toISOString()};var idx=arr('custos').findIndex(function(x){return x.id===id});if(idx<0)arr('custos').push(obj);else db.custos[idx]=obj;salvarNuvem(['custos']);limparCusto();render()}
function editarCusto(id){var x=arr('custos').find(function(y){return y.id===id});if(!x)return;var map={Data:'data',Competencia:'competencia',Veiculo:'veiculo',Motorista:'motorista',Categoria:'categoria',Tipo:'tipo',Descricao:'descricao',Valor:'valor',Status:'status',Rateio:'rateio',Observacao:'observacao'};Object.keys(map).forEach(function(s){var e=document.getElementById('cus'+s);if(e)e.value=x[map[s]]||''});document.getElementById('cusIdx').value=x.id;trocarAba('lancamentos');document.getElementById('cusData').scrollIntoView({behavior:'smooth',block:'center'})}
function excluirCusto(id){if(!confirm('Excluir este lançamento?'))return;var i=arr('custos').findIndex(function(x){return x.id===id});if(i<0)return;db.custos.splice(i,1);salvarNuvem(['custos']);render()}
function limparCusto(){['cusIdx','cusDescricao','cusValor','cusObservacao'].forEach(function(id){var e=document.getElementById(id);if(e)e.value=''});document.getElementById('cusData').value=hoje();document.getElementById('cusCompetencia').value=hoje().slice(0,7)}
function salvarRec(){var xid=val('cusRecIdx'),cat=val('cusRecCategoria'),valor=num(val('cusRecValor')),per=val('cusRecPeriodicidade')||'mensal';if(!cat||valor<=0){alert('Informe categoria e valor.');return}var obj={id:xid||uid('rec'),categoria:cat,tipo:val('cusRecTipo')||CATS[cat]||'fixo',veiculo:val('cusRecVeiculo'),motorista:val('cusRecMotorista'),descricao:val('cusRecDescricao'),valor:valor,periodicidade:per,inicio:val('cusRecInicio')||mesInicio(),fim:val('cusRecFim'),rateio:val('cusRecRateio')||'nao',ativo:true,atualizadoEm:new Date().toISOString()},ix=arr('custosRecorrentes').findIndex(function(x){return x.id===obj.id});if(ix<0)arr('custosRecorrentes').push(obj);else db.custosRecorrentes[ix]=obj;salvarNuvem(['custosRecorrentes']);cancelarRec();render()}
function salvarPessoal(){var salario=num(val('cusPesSalario')),veiculo=val('cusPesVeiculo'),motorista=val('cusPesMotorista'),inicio=val('cusPesInicio')||mesInicio();if(!veiculo||!motorista||salario<=0){alert('Informe veículo, motorista e salário-base.');return}var grupo=uid('folha'),itens=[['Salário',salario],['Encargos patronais',salario*num(val('cusPesEncargos'))/100],['FGTS',salario*num(val('cusPesFgts'))/100],['Benefícios',num(val('cusPesBeneficios'))],['13º salário',salario/12],['Férias + 1/3',salario/9]];itens.forEach(function(it){if(it[1]<=0)return;arr('custosRecorrentes').push({id:uid('pes'),grupoId:grupo,origem:'pessoal',categoria:it[0],tipo:'fixo',veiculo:veiculo,motorista:motorista,descricao:it[0]+' — '+motorista,valor:it[1],periodicidade:'mensal',inicio:inicio,rateio:'nao',ativo:true})});salvarNuvem(['custosRecorrentes']);['cusPesSalario','cusPesEncargos','cusPesFgts','cusPesBeneficios'].forEach(function(id){document.getElementById(id).value=''});render()}
function renderRecorrentes(){var el=document.getElementById('cusRecLista');if(!el)return;var p=paginar(arr('custosRecorrentes'),'paginaRecorrentes');el.innerHTML=p.itens.map(function(x){var mensal=x.periodicidade==='anual'?num(x.valor)/12:num(x.valor);return '<div class="cus-rec-row"><div><b>'+esc(x.descricao||x.categoria)+'</b><div class="cus-mini">'+esc(x.categoria)+' · '+esc(x.veiculo||'Frota geral')+(x.motorista?' · '+esc(x.motorista):'')+'</div></div><span>'+brl(mensal)+'/mês</span><span>'+(x.periodicidade==='anual'?brl(num(x.valor))+' anual':'Mensal')+'</span><span>'+esc(x.inicio||'--')+'</span><span class="cus-history-actions"><button class="btn-edit" onclick="editarCustoRecorrente(\''+esc(x.id)+'\')">✎ Editar</button><button class="btn-del" onclick="excluirCustoRecorrente(\''+esc(x.id)+'\')">✕ Excluir</button></span></div>'}).join('')||'<div class="cus-empty">Nenhum custo recorrente configurado.</div>';var pg=document.getElementById('cusRecPaginacao');if(pg)pg.innerHTML=p.html}
function editarRec(id){var x=arr('custosRecorrentes').find(function(y){return y.id===id});if(!x)return;var map={Idx:'id',Categoria:'categoria',Tipo:'tipo',Periodicidade:'periodicidade',Valor:'valor',Veiculo:'veiculo',Motorista:'motorista',Descricao:'descricao',Inicio:'inicio',Fim:'fim',Rateio:'rateio'};Object.keys(map).forEach(function(k){var e=document.getElementById('cusRec'+k);if(e)e.value=x[map[k]]||''});trocarAba('recorrentes')}
function cancelarRec(){['cusRecIdx','cusRecDescricao','cusRecValor','cusRecFim','cusRecVeiculo','cusRecMotorista'].forEach(function(id){var e=document.getElementById(id);if(e)e.value=''});var i=document.getElementById('cusRecInicio');if(i)i.value=mesInicio()}
function excluirRec(id){if(!confirm('Excluir este custo e suas provisões relacionadas?'))return;var alvo=arr('custosRecorrentes').find(function(x){return x.id===id}),grupo=alvo&&alvo.grupoId;db.custosRecorrentes=arr('custosRecorrentes').filter(function(x){return grupo?x.grupoId!==grupo:x.id!==id});salvarNuvem(['custosRecorrentes']);render()}
function salvarKm(){var xid=val('cusKmIdx'),v=val('cusKmVeiculo'),d=val('cusKmData'),ini=num(val('cusKmInicial')),fim=num(val('cusKmFinal')),km=num(val('cusKmRodado'))||(fim-ini);if(!v||!d||km<=0||fim&&ini&&fim<ini){alert('Confira veículo, data e quilometragem. O odômetro final não pode ser menor que o inicial.');return}var obj={id:xid||uid('km'),veiculo:v,data:d,kmRodado:km,odometroInicial:ini,odometroFinal:fim,observacao:val('cusKmObs'),confirmado:true,atualizadoEm:new Date().toISOString()},ix=arr('quilometragens').findIndex(function(x){return x.id===obj.id});if(ix<0)arr('quilometragens').push(obj);else db.quilometragens[ix]=obj;salvarNuvem(['quilometragens']);cancelarKm();render()}
function renderKm(){var el=document.getElementById('cusKmLista');if(!el)return;var p=paginar(arr('quilometragens').slice().sort(function(a,b){return data(b.data).localeCompare(data(a.data))}),'paginaKm');el.innerHTML=p.itens.map(function(x){return '<tr><td>'+esc(data(x.data).split('-').reverse().join('/'))+'</td><td><b>'+esc(x.veiculo)+'</b></td><td>'+num(x.kmRodado).toLocaleString('pt-BR')+' km</td><td>'+num(x.odometroInicial).toLocaleString('pt-BR')+'</td><td>'+num(x.odometroFinal).toLocaleString('pt-BR')+'</td><td>'+esc(x.observacao||'--')+'</td><td class="cus-history-actions"><button class="btn-edit" onclick="editarQuilometragem(\''+esc(x.id)+'\')">✎ Editar</button><button class="btn-del" onclick="excluirQuilometragem(\''+esc(x.id)+'\')">✕ Excluir</button></td></tr>'}).join('')||'<tr><td colspan="7" class="cus-empty">Cadastre os fechamentos manuais de quilometragem.</td></tr>';var pg=document.getElementById('cusKmPaginacao');if(pg)pg.innerHTML=p.html}
function editarKm(id){var x=arr('quilometragens').find(function(y){return y.id===id});if(!x)return;var map={Idx:'id',Veiculo:'veiculo',Data:'data',Rodado:'kmRodado',Inicial:'odometroInicial',Final:'odometroFinal',Obs:'observacao'};Object.keys(map).forEach(function(k){var e=document.getElementById('cusKm'+k);if(e)e.value=x[map[k]]||''});trocarAba('quilometragem')}
function cancelarKm(){['cusKmIdx','cusKmVeiculo','cusKmRodado','cusKmInicial','cusKmFinal','cusKmObs'].forEach(function(id){var e=document.getElementById(id);if(e)e.value=''});var d=document.getElementById('cusKmData');if(d)d.value=hoje()}
function excluirKm(id){if(!confirm('Excluir esta quilometragem?'))return;db.quilometragens=arr('quilometragens').filter(function(x){return x.id!==id});salvarNuvem(['quilometragens']);render()}
function periodo(tipo){var d=new Date(),ini,fim;if(tipo==='mes'){ini=new Date(d.getFullYear(),d.getMonth(),1);fim=new Date(d.getFullYear(),d.getMonth()+1,0)}else if(tipo==='anterior'){ini=new Date(d.getFullYear(),d.getMonth()-1,1);fim=new Date(d.getFullYear(),d.getMonth(),0)}else if(tipo==='tri'){ini=new Date(d.getFullYear(),d.getMonth()-2,1);fim=new Date(d.getFullYear(),d.getMonth()+1,0)}else{ini=new Date(d.getFullYear(),0,1);fim=new Date(d.getFullYear(),11,31)}document.getElementById('cusFiltroInicio').value=ini.getFullYear()+'-'+String(ini.getMonth()+1).padStart(2,'0')+'-'+String(ini.getDate()).padStart(2,'0');document.getElementById('cusFiltroFim').value=fim.getFullYear()+'-'+String(fim.getMonth()+1).padStart(2,'0')+'-'+String(fim.getDate()).padStart(2,'0');render()}
function trocarAba(nome){estado.tab=nome;document.querySelectorAll('.cus-tab').forEach(function(e){e.classList.toggle('active',e.dataset.tab===nome)});document.querySelectorAll('.cus-pane').forEach(function(e){e.classList.toggle('hidden',e.id!=='cusPane-'+nome)});render()}
function exportar(){var f=filtros(),l=filtrados(),det=l.map(function(x){return {'Data':x.data,'Competência':x.competencia,'Veículo':x.veiculo||'Frota geral','Motorista':x.motorista||'','Categoria':x.categoria,'Tipo':x.tipo,'Descrição':x.descricao,'Origem':x.origem,'Situação':x.status,'Valor (R$)':x.valor}});if(!det.length){alert('Não há dados para exportar.');return}var wb=XLSX.utils.book_new(),ws=XLSX.utils.json_to_sheet(det),placas=f.v?[f.v]:veiculosGestao(),res=[];placas.forEach(function(p){var itens=filtrados(p),t=itens.reduce(function(s,x){return s+x.valor},0),km=kmPeriodo(p,f.ini,f.fim),fat=faturamentoPeriodo(p,f.ini,f.fim),liq=receitaLiquidaPeriodo(p,f.ini,f.fim);if(t||km||fat||liq)res.push({'Veículo':p,'Faturamento total (R$)':fat,'Receita líquida (R$)':liq,'Custo total (R$)':t,'KM':km,'Custo por KM (R$)':km?t/km:0})});XLSX.utils.book_append_sheet(wb,ws,'Lançamentos manuais');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(res),'Resumo por veículo');XLSX.writeFile(wb,'FrotaMaster_Gestao_Frota_'+hoje()+'.xlsx')}
function veiculosGestao(){var m={};arr('veiculos').forEach(function(v){if(v.vplaca)m[v.vplaca]=true});['custos','custosRecorrentes','quilometragens','producoes','metasVeiculos','gestaoDepreciacoes'].forEach(function(k){arr(k).forEach(function(x){if(x.veiculo)m[x.veiculo]=true})});return Object.keys(m).sort()}
function categoriaChange(prefix){var cat=val(prefix+'Categoria'),e=document.getElementById(prefix+'Tipo');if(e&&CATS[cat])e.value=CATS[cat]}
function init(){var root=document.getElementById('custos');if(!root)return;migrarIds();var cats='<option value="">Todas as categorias</option>'+Object.keys(CATS).map(function(k){return '<option value="'+esc(k)+'">'+esc(k)+'</option>'}).join('');document.getElementById('cusFiltroCategoria').innerHTML=cats;['cusCategoria','cusRecCategoria'].forEach(function(id){document.getElementById(id).innerHTML=cats.replace('<option value="">Todas as categorias</option>','<option value="">Selecione...</option>')});document.getElementById('cusFiltroInicio').value=mesInicio();document.getElementById('cusFiltroFim').value=mesFim();document.getElementById('cusData').value=hoje();document.getElementById('cusCompetencia').value=hoje().slice(0,7);document.getElementById('cusRecInicio').value=mesInicio();document.getElementById('cusPesInicio').value=mesInicio();document.getElementById('cusKmData').value=hoje();root.querySelectorAll('[data-cus-filter]').forEach(function(e){e.addEventListener('change',render)});render()}
var prev=window.renderModulo;window.renderModulo=function(mod){if(mod==='custos'){render();return}return typeof prev==='function'?prev.apply(this,arguments):undefined};
window.mudarPaginaGestao=function(chave,p){estado[chave]=p;render()};window.FMCustosAPI={filtrados:filtrados,filtros:filtros,kmPeriodo:kmPeriodo,todosBase:todosBase,brl:brl,num:num,veiculos:veiculosGestao};window.renderCustosFrota=render;window.salvarCustoFrota=salvarCusto;window.editarCustoFrota=editarCusto;window.excluirCustoFrota=excluirCusto;window.limparCustoFrota=limparCusto;window.salvarCustoRecorrente=salvarRec;window.editarCustoRecorrente=editarRec;window.cancelarCustoRecorrente=cancelarRec;window.salvarCustoPessoal=salvarPessoal;window.cancelarCustoPessoal=function(){['cusPesVeiculo','cusPesMotorista','cusPesSalario','cusPesEncargos','cusPesFgts','cusPesBeneficios'].forEach(function(id){var e=document.getElementById(id);if(e)e.value=''})};window.excluirCustoRecorrente=excluirRec;window.salvarQuilometragem=salvarKm;window.editarQuilometragem=editarKm;window.cancelarQuilometragem=cancelarKm;window.excluirQuilometragem=excluirKm;window.aplicarPeriodoCustos=periodo;window.trocarAbaCustos=trocarAba;window.exportarCustosFrota=exportar;window.custoCategoriaChange=categoriaChange;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
