(function(){
'use strict';
var CATS={
 'Depreciação':'fixo','Remuneração do capital':'fixo','Financiamento / Leasing':'fixo','Seguro':'fixo','IPVA / Licenciamento':'fixo','Rastreamento / Telemetria':'fixo','Garagem / Estacionamento':'fixo','Documentação / Taxas':'fixo',
 'Salário':'fixo','Encargos patronais':'fixo','FGTS':'fixo','13º salário':'fixo','Férias + 1/3':'fixo','Benefícios':'fixo',
 'Combustível':'variavel','ARLA 32':'variavel','Pedágio':'variavel','Estacionamento em viagem':'variavel','Pneus / Recapagem':'variavel','Manutenção preventiva':'variavel','Manutenção corretiva':'variavel','Peças':'variavel','Lubrificantes / Filtros':'variavel','Lavagem':'variavel','Multas':'variavel','Diárias / Adicionais':'variavel','Custos administrativos':'indireto','Outros custos fixos':'fixo','Outros custos variáveis':'variavel'
};
var estado={chart:null,tab:'lancamentos',paginaLancamentos:1,paginaPreLancamentos:1,paginaRecorrentes:1,paginaKm:1,paginaVeiculos:1,itensPagina:15,renderizando:false,renderPendente:false};
var confirmacaoPreEmAndamento=false;
function arr(k){return typeof db!=='undefined'&&Array.isArray(db[k])?db[k]:[]}
function uid(p){return (p||'id')+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,9)}
function num(v){if(typeof v==='number')return isFinite(v)?v:0;if(typeof moedaParaFloat==='function')return moedaParaFloat(v);return Number(String(v||0).replace(/R\$\s?/g,'').replace(/\./g,'').replace(',','.'))||0}
function brl(v){return (Number(v)||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function data(v){if(!v)return '';var s=String(v).trim();if(/^\d{4}-\d{2}-\d{2}/.test(s))return s.slice(0,10);var p=s.match(/(\d{2})[\/.-](\d{2})[\/.-](\d{2,4})/);if(!p)return '';return (p[3].length===2?'20'+p[3]:p[3])+'-'+p[2]+'-'+p[1]}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function hoje(){return new Date().toISOString().slice(0,10)}
function mesInicio(d){var x=d?new Date(d+'T12:00:00'):new Date();return x.getFullYear()+'-'+String(x.getMonth()+1).padStart(2,'0')+'-01'}
function mesFim(d){var x=d?new Date(d+'T12:00:00'):new Date();return new Date(x.getFullYear(),x.getMonth()+1,0).toISOString().slice(0,10)}
function val(id){var e=document.getElementById(id);return e?e.value:''}
function set(id,v){var e=document.getElementById(id);if(e)e.textContent=v}
function mesChave(d){return data(d).slice(0,7)}
function adicionarMes(comp,quantidade){var p=String(comp||'').slice(0,7).split('-'),d=new Date(Number(p[0]),Number(p[1])-1+(quantidade||0),1);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')}
function expandirParcelas(x){var qtd=Math.max(1,Math.min(120,Math.floor(num(x.parcelas)||1))),comp=x.competencia||mesChave(x.data),totalCentavos=Math.round(num(x.valor)*100),base=Math.floor(totalCentavos/qtd),resto=totalCentavos-base*qtd;if(qtd===1)return [Object.assign({},x,{parcelas:1,parcelaAtual:1,valor:totalCentavos/100})];return Array.from({length:qtd},function(_,i){var competencia=adicionarMes(comp,i),valor=(base+(i<resto?1:0))/100;return Object.assign({},x,{id:x.id+'-parcela-'+(i+1),lancamentoId:x.id,competencia:competencia,data:competencia+'-01',parcelas:qtd,parcelaAtual:i+1,valorTotal:num(x.valor),valor:valor,parcelaCalculada:true})})}
function mesesPeriodo(inicio,fim){var a=new Date(mesInicio(inicio)+'T12:00:00'),b=new Date(mesFim(fim)+'T12:00:00');return Math.max(1,(b.getFullYear()-a.getFullYear())*12+b.getMonth()-a.getMonth()+1)}
function veiculoMotorista(placa){var v=arr('veiculos').find(function(x){return x.vplaca===placa});return v&&v.vmotorista||''}
function normalizarPlaca(v){return String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'')}
function veiculoVendido(placa){var p=normalizarPlaca(placa),v=arr('veiculos').find(function(x){return normalizarPlaca(x.vplaca)===p});return !!v&&String(v.vstatus||'').trim().toUpperCase()==='VENDIDO'}
function validarVeiculoNovo(placa,idEdicao){if(placa&&veiculoVendido(placa)&&!idEdicao){alert('Este veículo está marcado como vendido e não pode receber novos registros.');return false}return true}
function hashRegistro(x){return [normalizarPlaca(x.veiculo),data(x.data),x.categoria,Number(x.valor||0).toFixed(2)].join('|')}
function origem(lista,mod,cat,tipo,placaCampo,dataCampo,valorFn,descFn){arr(mod).forEach(function(x,i){var valor=valorFn(x),dt=data(x[dataCampo]);if(valor<=0||!dt)return;lista.push({id:'auto-'+mod+'-'+(x.id||i),automatico:true,origem:mod,categoria:cat,tipo:tipo,veiculo:x[placaCampo]||'',motorista:veiculoMotorista(x[placaCampo]),data:dt,competencia:dt.slice(0,7),descricao:descFn(x),valor:valor,status:'Realizado'})})}
function origemAnual(lista,mod,cat,placaCampo,dataCampo,valorCampo,descricao){arr(mod).forEach(function(x,i){var total=num(x[valorCampo]),dt=data(x[dataCampo]);if(total<=0||!dt)return;for(var m=1;m<=12;m++){var ds=dt.slice(0,4)+'-'+String(m).padStart(2,'0')+'-01';lista.push({id:'auto-'+mod+'-'+(x.id||i)+'-'+m,automatico:true,origem:mod,categoria:cat,tipo:'fixo',veiculo:x[placaCampo]||'',motorista:veiculoMotorista(x[placaCampo]),data:ds,competencia:ds.slice(0,7),descricao:'Apropriação mensal — '+descricao,valor:total/12,status:'Provisionado',periodicidade:'anual'})}})}
function competenciaAtual(){var d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')}
 function origemId(mod,x,i){return mod+':'+String(x.id||x._id||x._rid||x._fid||x.uid||i)}
function categoriaManutencao(x){var s=String(x.mservico||'').toLowerCase();if(/prevent|revis/.test(s))return 'Manutenção preventiva';if(/óleo|oleo|lubr|filtro/.test(s))return 'Lubrificantes / Filtros';if(/peça|peca/.test(s))return 'Peças';return 'Manutenção corretiva'}
function candidatosPreLancamento(){var out=[];function add(mod,x,i,cfg){var valor=num(cfg.valor(x)),dt=data(cfg.data(x)),chave=origemId(mod,x,i),parcelas=cfg.parcelas?Math.max(1,Math.floor(num(cfg.parcelas(x)))||1):1;if(valor<=0||!dt)return;out.push({id:'pre-'+chave.replace(/[^a-zA-Z0-9_-]/g,'-'),origemChave:chave,origemModulo:mod,origemNome:cfg.nome,origemRegistroId:String(x.id||x._id||x._rid||x._fid||x.uid||i),data:dt,competencia:dt.slice(0,7),veiculo:cfg.veiculo(x)||'',motorista:cfg.motorista?cfg.motorista(x)||'':veiculoMotorista(cfg.veiculo(x)),categoria:typeof cfg.categoria==='function'?cfg.categoria(x):cfg.categoria,tipo:cfg.tipo||CATS[typeof cfg.categoria==='function'?cfg.categoria(x):cfg.categoria]||'variavel',descricao:cfg.descricao(x),valor:valor,parcelas:parcelas,status:'Pendente',rateio:'nao',situacaoPre:'pendente',atualizadoEm:new Date().toISOString()})}
 var specs={
  combustivel:{nome:'Combustível',veiculo:function(x){return x.cveiculo},data:function(x){return x.cdata},valor:function(x){return num(x.ctotal)||num(x.clitros)*num(x.cvalorlitro)},categoria:'Combustível',descricao:function(x){return 'Abastecimento'+(x.ctipo?' — '+x.ctipo:'')+(x.cposto?' — '+x.cposto:'')}},
  manutencoes:{nome:'Manutenções',veiculo:function(x){return x.mveiculo},data:function(x){return x.mdata},valor:function(x){return num(x.mtotalnf)||num(x.mvalor)+num(x.mvalornfse)},parcelas:function(x){return x.mpagamento==='parcelado'?x.mparcelas:1},categoria:categoriaManutencao,descricao:function(x){return x.mservico||'Manutenção do veículo'}},
  multas:{nome:'Multas',veiculo:function(x){return x.muveiculo},motorista:function(x){return x.mumotorista},data:function(x){return x.mudata||x.muvenc},valor:function(x){return x.muvalor},categoria:'Multas',descricao:function(x){return x.muinfracao||('Multa '+(x.muait||''))}},
  licenciamento:{nome:'Licenciamento',veiculo:function(x){return x.lveiculo},data:function(x){return x.lvencimento},valor:function(x){return x.lvalor},categoria:'IPVA / Licenciamento',tipo:'fixo',descricao:function(){return 'Licenciamento / IPVA'}},
  tacografo:{nome:'Tacógrafo',veiculo:function(x){return x.tveiculo},data:function(x){return x.tdataafericao||x.tvencimento},valor:function(x){return x.tvalor},categoria:'Documentação / Taxas',tipo:'fixo',descricao:function(){return 'Aferição de tacógrafo'}},
  licencas:{nome:'CIV / CIPP',veiculo:function(x){return x.leveiculo},data:function(x){return x.venciv||x.vencipp},valor:function(x){return x.levalor},categoria:'Documentação / Taxas',tipo:'fixo',descricao:function(x){return 'CIV / CIPP'+(x.numciv?' — CIV '+x.numciv:'')+(x.numcipp?' — CIPP '+x.numcipp:'')}},
  diarias:{nome:'Diárias',veiculo:function(x){return x.diveiculo||''},motorista:function(x){return x.dimotorista},data:function(x){return x.didata},valor:function(x){return x.divalor},categoria:'Diárias / Adicionais',descricao:function(x){return 'Diária'+(x.dicoleta?' — coleta/entrega '+x.dicoleta:'')}},
  revisoes:{nome:'Revisões KM',veiculo:function(x){return x.rveiculo},data:function(x){return x.rdata||x.rdatarealizada},valor:function(x){return x.rvalor},categoria:'Manutenção preventiva',descricao:function(x){return x.rservico||x.rtipo||'Revisão por quilometragem'}}
 };
 Object.keys(specs).forEach(function(mod){if(window.fmModuloCarregado&& !window.fmModuloCarregado(mod))return;arr(mod).forEach(function(x,i){if(!specs[mod].ignorar||!specs[mod].ignorar(x))add(mod,x,i,specs[mod])})});return out}
function moduloPronto(mod){return typeof window.fmModuloCarregado!=='function'?true:!!window.fmModuloCarregado(mod)}
// O banco e a unica fonte. Sem a leitura confirmada de preLancamentos e custos,
// recriar candidatos gera copias novas dos itens ja confirmados: eles voltam a
// lista depois de atualizar a pagina e a contagem cresce a cada recarga.
function prePronto(){return moduloPronto('preLancamentos')&&moduloPronto('custos')}
function deduplicarPre(){var vistos={},saida=[],mudou=false;arr('preLancamentos').forEach(function(x){var ch=x&&x.origemChave;if(!ch){saida.push(x);return}var ant=vistos[ch];if(!ant){vistos[ch]=x;saida.push(x);return}mudou=true;var peso=function(y){return y.situacaoPre==='confirmado'?3:y.situacaoPre==='descartado'?2:y.editadoManualmente?1:0};if(peso(x)>peso(ant)){saida[saida.indexOf(ant)]=x;vistos[ch]=x}});if(mudou)db.preLancamentos=saida;return mudou}
function sincronizarPreLancamentos(){if(typeof db==='undefined')return false;if(!Array.isArray(db.preLancamentos))db.preLancamentos=[];if(!prePronto())return false;var mudouLista=deduplicarPre(),atuais={},porOrigem={},custosPorOrigem={};db.preLancamentos.forEach(function(x){if(x&&x.origemChave)porOrigem[x.origemChave]=x});arr('custos').forEach(function(x){if(x&&x.origemChave)custosPorOrigem[x.origemChave]=true});candidatosPreLancamento().forEach(function(novo){if(!moduloPronto(novo.origemModulo))return;atuais[novo.origemChave]=true;var existente=porOrigem[novo.origemChave];if(!existente){if(!custosPorOrigem[novo.origemChave]){db.preLancamentos.push(novo);porOrigem[novo.origemChave]=novo;mudouLista=true}return}if(existente.situacaoPre==='descartado'||existente.situacaoPre==='confirmado'||existente.editadoManualmente)return;var mudou=false;['data','competencia','veiculo','motorista','categoria','tipo','descricao','valor','parcelas','origemNome','origemRegistroId'].forEach(function(k){if(existente[k]!==novo[k]){existente[k]=novo[k];mudou=true}});if(mudou){existente.atualizadoEm=novo.atualizadoEm;mudouLista=true}});var tamanhoAntes=db.preLancamentos.length;db.preLancamentos=db.preLancamentos.filter(function(x){if(x.situacaoPre==='confirmado'||x.situacaoPre==='descartado')return true;if(!moduloPronto(x.origemModulo))return true;return !!atuais[x.origemChave]});return mudouLista||tamanhoAntes!==db.preLancamentos.length}
function automaticos(){return []}
function recorrentes(inicio,fim){var out=[];arr('custosRecorrentes').forEach(function(r,ri){if(r.ativo===false)return;var start=data(r.inicio)||inicio,end=data(r.fim)||fim,ini=new Date(start+'T12:00:00'),limI=new Date(inicio+'T12:00:00'),limF=new Date(fim+'T12:00:00'),limEnd=new Date(end+'T12:00:00');if(!isFinite(ini.getTime())||!isFinite(limI.getTime())||!isFinite(limF.getTime())||!isFinite(limEnd.getTime()))return;if(ini<limI)ini=limI;var cur=new Date(ini.getFullYear(),ini.getMonth(),1),valor=r.periodicidade==='anual'?num(r.valor)/12:num(r.valor),guard=0;while(cur<=limF&&cur<=limEnd&&guard<600){var ds=cur.getFullYear()+'-'+String(cur.getMonth()+1).padStart(2,'0')+'-01';out.push({id:'rec-'+(r.id||ri)+'-'+ds,automatico:true,projecaoRecorrente:true,origem:r.origem||'recorrente',categoria:r.categoria,tipo:r.tipo||CATS[r.categoria]||'fixo',veiculo:r.veiculo||'',motorista:r.motorista||'',data:ds,competencia:ds.slice(0,7),descricao:r.descricao||r.categoria,valor:valor,status:'Provisionado',rateio:r.rateio||'nao',periodicidade:r.periodicidade||'mensal'});cur=new Date(cur.getFullYear(),cur.getMonth()+1,1);guard++}});return out}
function periodoCompleto(){var datas=[];['custos','preLancamentos','quilometragens'].forEach(function(k){arr(k).forEach(function(x){var d=data(x.data);if(d)datas.push(d)})});arr('custosRecorrentes').forEach(function(x){var ini=data(x.inicio),fim=data(x.fim);if(ini)datas.push(ini);if(fim)datas.push(fim)});datas.sort();return {ini:datas[0]||mesInicio(),fim:datas[datas.length-1]||mesFim()}}
function filtros(){var periodo=periodoCompleto();return {v:val('cusFiltroVeiculo'),ini:val('cusFiltroInicio')||periodo.ini,fim:val('cusFiltroFim')||periodo.fim,tipo:val('cusFiltroTipo'),cat:val('cusFiltroCategoria'),origem:val('cusFiltroOrigem'),status:val('cusFiltroStatus'),modo:val('cusFiltroModo')||'competencia'}}
function migrarIds(){var mudou=[];['custos','custosRecorrentes','quilometragens','importacoesPedagio'].forEach(function(k){arr(k).forEach(function(x){if(!x.id){x.id=uid(k);if(mudou.indexOf(k)<0)mudou.push(k)}})});if(mudou.length&&typeof salvarNuvem==='function')salvarNuvem(mudou)}
function todosBase(){var f=filtros(),manuais=[];arr('custos').forEach(function(x){var item=Object.assign({automatico:false,origem:'manual'},x,{valor:num(x.valor),data:data(x.data),id:x.id||uid('cus')});if(item.origem==='pedagio_importado'&&Array.isArray(item.detalhesPedagio)){var ds=item.detalhesPedagio.filter(function(d){var dt=data(d.data);return (!f.ini||dt>=f.ini)&&(!f.fim||dt<=f.fim)});item.valor=ds.reduce(function(t,d){return t+num(d.valor)},0);if(!ds.length)item.valor=0}if(item.origem!=='pedagio_importado'||item.valor>0)manuais.push.apply(manuais,expandirParcelas(item))});var vistos={};manuais.forEach(function(m){vistos[hashRegistro(m)]=true});var auto=automaticos().filter(function(a){var h=hashRegistro(a);if(vistos[h])return false;vistos[h]=true;return true});var reais={};manuais.forEach(function(m){var comp=m.competencia||mesChave(m.data);reais[String(m.categoria||'')+'|'+normalizarPlaca(m.veiculo)+'|'+comp]=true});var projecoes=recorrentes(f.ini,f.fim).filter(function(r){return !reais[String(r.categoria||'')+'|'+normalizarPlaca(r.veiculo)+'|'+(r.competencia||mesChave(r.data))]});return manuais.concat(auto).concat(projecoes)}
function kmPeriodo(placa,ini,fim){return arr('quilometragens').filter(function(x){return (!placa&&!veiculoVendido(x.veiculo)||normalizarPlaca(x.veiculo)===normalizarPlaca(placa))&&data(x.data)>=ini&&data(x.data)<=fim}).reduce(function(s,x){return s+Math.max(0,num(x.kmRodado)||(num(x.odometroFinal)-num(x.odometroInicial)))},0)}
function faturamentoPeriodo(placa,ini,fim){return arr('producoes').filter(function(x){if(x.statusOperacional==='Cancelada'||(!placa&&veiculoVendido(x.veiculo))||(placa&&normalizarPlaca(x.veiculo)!==normalizarPlaca(placa)))return false;var competencia=x.competencia||mesChave(x.dataFim||x.dataInicio),dt=competencia?competencia+'-01':data(x.dataFim||x.dataInicio);return !!dt&&dt>=mesInicio(ini)&&dt<=mesFim(fim)}).reduce(function(s,x){return s+num(x.receitaBruta)},0)}
function receitaLiquidaPeriodo(placa,ini,fim){return arr('producoes').filter(function(x){if(x.statusOperacional==='Cancelada'||(!placa&&veiculoVendido(x.veiculo))||(placa&&normalizarPlaca(x.veiculo)!==normalizarPlaca(placa)))return false;var competencia=x.competencia||mesChave(x.dataFim||x.dataInicio),dt=competencia?competencia+'-01':data(x.dataFim||x.dataInicio);return !!dt&&dt>=mesInicio(ini)&&dt<=mesFim(fim)}).reduce(function(s,x){return s+num(x.receitaBruta)-num(x.descontos)-num(x.impostos)+num(x.ajuste)},0)}
function ratearParaVeiculo(x,placa,f){if(x.veiculo)return normalizarPlaca(x.veiculo)===normalizarPlaca(placa)?x:null;if(x.rateio==='igual'){var vs=veiculosGestao();return vs.some(function(v){return normalizarPlaca(v)===normalizarPlaca(placa)})?Object.assign({},x,{veiculo:placa,valor:x.valor/vs.length,rateado:true}):null}if(x.rateio==='km'){var total=kmPeriodo('',f.ini,f.fim),km=kmPeriodo(placa,f.ini,f.fim);return total&&km?Object.assign({},x,{veiculo:placa,valor:x.valor*km/total,rateado:true}):null}return null}
function filtrados(placaForcada,filtroForcado,baseForcada){var f=filtroForcado||filtros(),placa=placaForcada===undefined?f.v:placaForcada,l=baseForcada||todosBase();if(placa)l=l.map(function(x){return ratearParaVeiculo(x,placa,f)}).filter(Boolean);return l.filter(function(x){var comp=(x.competencia||mesChave(x.data)),di=f.modo==='caixa'?data(x.data):(comp?comp+'-01':data(x.data));return (!f.ini||di>=(f.modo==='caixa'?data(f.ini):mesInicio(f.ini)))&&(!f.fim||di<=(f.modo==='caixa'?data(f.fim):mesFim(f.fim)))&&(!f.tipo||x.tipo===f.tipo)&&(!f.cat||x.categoria===f.cat)&&(!f.origem||x.origem===f.origem)&&(!f.status||x.status===f.status)}).sort(function(a,b){return (b.competencia||b.data||'').localeCompare(a.competencia||a.data||'')})}
function preencherSelects(){var ativos=arr('veiculos').filter(function(v){return !veiculoVendido(v.vplaca)}),opts='<option value="">Todos os veículos ativos</option>'+ativos.map(function(v){return '<option value="'+esc(v.vplaca)+'">'+esc(v.vplaca)+' — '+esc(v.vmodelo||'')+'</option>'}).join(''),f=document.getElementById('cusFiltroVeiculo'),old=f&&f.value;if(f){f.innerHTML=opts;f.value=ativos.some(function(v){return v.vplaca===old})?old:''}var dl=document.getElementById('cusVeiculosLista');if(dl)dl.innerHTML=ativos.map(function(v){return '<option value="'+esc(v.vplaca)+'">'+esc(v.vmodelo||'')+'</option>'}).join('');var ml=document.getElementById('cusMotoristasLista');if(ml)ml.innerHTML=arr('motoristas').filter(function(m){return String(m.motStatus||'ATIVO').toUpperCase()!=='INATIVO'}).map(function(m){var nome=m.motNome||m.mnome||m.nome||'';return '<option value="'+esc(nome)+'"></option>'}).join('');var pl=document.getElementById('cusPneusLista');if(pl)pl.innerHTML=arr('pneus').map(function(p){return '<option value="'+esc(p.pnumero||p.pid||'')+'"></option>'}).join('')}
function abaAtiva(){var ativa=document.querySelector('#custos .cus-tab.active');return ativa&&ativa.dataset.tab||estado.tab}
function render(pularSincronizacao){if(!document.getElementById('custos'))return;if(estado.renderizando){estado.renderPendente=true;return}estado.renderizando=true;try{preencherSelects();var aba=abaAtiva();if(['lancamentos','recorrentes','pessoal','quilometragem','analise'].indexOf(aba)<0)return;if(aba==='lancamentos'&&!pularSincronizacao)sincronizarPreLancamentos();var f=filtros(),base=todosBase(),l=filtrados(undefined,f,base).filter(function(x){return f.v||!x.veiculo||!veiculoVendido(x.veiculo)}),total=l.reduce(function(s,x){return s+x.valor},0),faturamento=faturamentoPeriodo(f.v,f.ini,f.fim),receitaLiquida=receitaLiquidaPeriodo(f.v,f.ini,f.fim),km=kmPeriodo(f.v,f.ini,f.fim),margem=receitaLiquida?(receitaLiquida-total)/receitaLiquida*100:0;if(window.FMResultadoAPI){var integrado=window.FMResultadoAPI.totalGeral(f,f.modo,base);window.FMResultadoAPI.atualizarIndicadores(integrado,f)}else{set('cusIndicadorCustoKm',km?brl(total/km):'Sem leitura');set('cusIndicadorFaturamentoMedio',brl(faturamento/mesesPeriodo(f.ini,f.fim)));set('cusIndicadorCustoFrota',brl(total));set('cusIndicadorMargem',margem.toFixed(1).replace('.',',')+'%')}set('cusPeriodoLabel',f.ini.slice(0,7)===f.fim.slice(0,7)?'Competência '+f.ini.slice(0,7).split('-').reverse().join('/'):'Período selecionado');if(aba==='lancamentos'){renderPreLancamentos();renderTabela(l)}else if(aba==='recorrentes'||aba==='pessoal')renderRecorrentes();else if(aba==='quilometragem')renderKm();else if(aba==='analise'){renderCategorias(l,total);renderVeiculos(f,base);renderPendencias(l,f,km);grafico(l)}}finally{estado.renderizando=false;if(estado.renderPendente){estado.renderPendente=false;setTimeout(function(){render(true)},0)}}}
function prePendentes(){return arr('preLancamentos').filter(function(x){return x.situacaoPre!=='descartado'&&x.situacaoPre!=='confirmado'})}
function preFiltrados(){var f=filtros();return prePendentes().filter(function(x){var dt=data(x.data),origem=x.origem||'integrado';return (!f.v||normalizarPlaca(x.veiculo)===normalizarPlaca(f.v))&&(!f.ini||dt>=data(f.ini))&&(!f.fim||dt<=data(f.fim))&&(!f.tipo||x.tipo===f.tipo)&&(!f.cat||x.categoria===f.cat)&&(!f.origem||origem===f.origem)}).sort(function(a,b){return String(b.data).localeCompare(String(a.data))})}
var salvarPreAgendado=null;
function agendarSalvarPre(){if(salvarPreAgendado)clearTimeout(salvarPreAgendado);salvarPreAgendado=setTimeout(function(){salvarPreAgendado=null;if(confirmacaoPreEmAndamento)return;window.fmPularSincronizacaoPreUmaVez=true;try{salvarNuvem(['preLancamentos'])}catch(e){}},800)}
function renderPreLancamentos(){var f=filtros(),lista=preFiltrados(),tb=document.getElementById('cusPreLista'),p=paginar(lista,'paginaPreLancamentos');set('cusPreContador',String(lista.length));if(!tb)return;var cats=Object.keys(CATS).map(function(k){return '<option value="'+esc(k)+'">'+esc(k)+'</option>'}).join('');tb.innerHTML=p.itens.length?p.itens.map(function(x){var invalido=!x.data||!x.categoria||num(x.valor)<=0;return '<tr class="'+(invalido?'cus-pre-row-invalid':'')+'"><td><input type="checkbox" class="cus-check cus-pre-selecao" value="'+esc(x.id)+'" aria-label="Selecionar pré-lançamento"></td><td><input type="date" class="form-control" value="'+esc(x.data)+'" onchange="editarPreLancamento(\''+esc(x.id)+'\',\'data\',this.value)"></td><td><input class="form-control" list="cusVeiculosLista" value="'+esc(x.veiculo)+'" onchange="editarPreLancamento(\''+esc(x.id)+'\',\'veiculo\',this.value)"></td><td><select class="form-select" onchange="editarPreLancamento(\''+esc(x.id)+'\',\'categoria\',this.value)">'+cats.replace('value="'+esc(x.categoria)+'"','value="'+esc(x.categoria)+'" selected')+'</select></td><td><input class="form-control cus-pre-desc" value="'+esc(x.descricao)+'" onchange="editarPreLancamento(\''+esc(x.id)+'\',\'descricao\',this.value)"></td><td><select class="form-select" onchange="editarPreLancamento(\''+esc(x.id)+'\',\'tipo\',this.value)"><option value="fixo" '+(x.tipo==='fixo'?'selected':'')+'>Fixo</option><option value="variavel" '+(x.tipo==='variavel'?'selected':'')+'>Variável</option><option value="indireto" '+(x.tipo==='indireto'?'selected':'')+'>Indireto</option></select></td><td><b>'+esc(x.origemNome)+'</b><span class="cus-pre-origin">'+esc(x.origemRegistroId)+'</span></td><td><input class="form-control cus-pre-value" value="'+esc(brl(x.valor))+'" oninput="mascaraMoeda(this)" onchange="editarPreLancamento(\''+esc(x.id)+'\',\'valor\',this.value)"></td><td class="cus-history-actions"><button class="btn-edit" onclick="confirmarPreLancamento(\''+esc(x.id)+'\')">✓ Confirmar</button><button class="btn-del" onclick="descartarPreLancamento(\''+esc(x.id)+'\')">✕ Descartar</button></td></tr>'}).join(''):'<tr><td colspan="9" class="cus-empty">Nenhum pré-lançamento aguardando conferência com os filtros selecionados.</td></tr>';var pg=document.getElementById('cusPrePaginacao');if(pg)pg.innerHTML=p.html;var todos=document.getElementById('cusPreTodos');if(todos)todos.checked=false}
function editarPre(id,campo,valor){var x=arr('preLancamentos').find(function(y){return y.id===id});if(!x)return;if(campo==='valor')valor=num(valor);x[campo]=valor;if(campo==='data')x.competencia=data(valor).slice(0,7);if(campo==='categoria'&&CATS[valor])x.tipo=CATS[valor];x.editadoManualmente=true;x.atualizadoEm=new Date().toISOString();agendarSalvarPre()}
function validarPre(x){if(!x)return 'Registro não encontrado.';if(!data(x.data))return 'Data inválida.';if(!x.categoria||!CATS[x.categoria])return 'Categoria inválida.';if(num(x.valor)<=0)return 'Valor deve ser maior que zero.';return ''}
function contextoConfirmacaoPre(){var origens={},hashes={},recorrentes={};arr('custos').forEach(function(c){if(c.origemChave)origens[c.origemChave]=true;if(c.origem!=='integrado')hashes[hashRegistro(c)]=true});arr('custosRecorrentes').forEach(function(r){var chave=String(r.categoria||'')+'|'+normalizarPlaca(r.veiculo);if(!recorrentes[chave])recorrentes[chave]=[];recorrentes[chave].push(r)});return {origens:origens,hashes:hashes,recorrentes:recorrentes}}
function aplicarConfirmacaoPre(id,modoLote,contexto){var lista=arr('preLancamentos'),indice=lista.findIndex(function(y){return y.id===id&&y.situacaoPre!=='descartado'&&y.situacaoPre!=='confirmado'}),x=indice>=0?lista[indice]:null;if(!x)return {ok:true,correcao:false,jaProcessado:true};var erro=validarPre(x);if(erro)return {ok:false,correcao:true,erro:erro};var ctx=contexto||contextoConfirmacaoPre(),comp=x.competencia||data(x.data).slice(0,7),chaveRec=String(x.categoria||'')+'|'+normalizarPlaca(x.veiculo),recorrente=(ctx.recorrentes[chaveRec]||[]).some(function(r){return recAtivoNaCompetencia(r,comp)});if(recorrente&&!modoLote&&!confirm('Este custo de "'+x.categoria+'"'+(x.veiculo?' para '+x.veiculo:'')+' ja esta cadastrado em Fixos e pessoal e entra sozinho na competencia '+comp+'.\n\nConfirmar aqui vai contar o valor duas vezes.\n\nDeseja confirmar mesmo assim?'))return {ok:false,correcao:false,cancelado:true};var hash=hashRegistro(x),existente=!!(x.origemChave&&ctx.origens[x.origemChave])||!!ctx.hashes[hash];if(!existente){arr('custos').push({id:uid('cus'),data:data(x.data),competencia:comp,veiculo:x.veiculo||'',motorista:x.motorista||'',categoria:x.categoria,tipo:x.tipo||CATS[x.categoria]||'variavel',descricao:x.descricao,valor:num(x.valor),parcelas:Math.max(1,Math.floor(num(x.parcelas))||1),status:'Realizado',rateio:'nao',observacao:'Confirmado a partir de '+(x.origemNome||'outro modulo')+(recorrente?' | Atencao: ja existe custo fixo semelhante em Fixos e pessoal':''),origem:'integrado',origemChave:x.origemChave,origemModulo:x.origemModulo,origemRegistroId:x.origemRegistroId,atualizadoEm:new Date().toISOString()});if(x.origemChave)ctx.origens[x.origemChave]=true;ctx.hashes[hash]=true}var agora=new Date().toISOString();x.situacaoPre='confirmado';x.confirmadoEm=agora;x.atualizadoEm=agora;return {ok:true,correcao:false,duplicado:existente,duplicidade:!!recorrente}}
function persistirConfirmacoes(processados,correcoes){renderPreLancamentos();if(!processados){confirmacaoPreEmAndamento=false;window.fmConfirmacaoPreEmAndamento=false;if(correcoes)alert(correcoes+' pre-lancamento(s) precisam de correcao e permaneceram na lista.');return Promise.resolve(false)}estado.renderCompletoBloqueadoAte=Date.now()+15000;window.fmPularSincronizacaoPreUmaVez=true;window.fmConfirmacaoPreEmAndamento=true;return new Promise(function(resolve){setTimeout(resolve,0)}).then(function(){return typeof window.fmSalvarConfirmacoesPre==='function'?window.fmSalvarConfirmacoesPre():salvarNuvem(['custos','preLancamentos'])}).then(function(ok){if(ok===false){alert('Nao foi possivel confirmar a gravacao. Os dados continuam na tela: tente salvar novamente.');return false}if(correcoes)alert(processados+' pre-lancamento(s) confirmado(s). '+correcoes+' precisam de correcao e permaneceram na lista.');return true}).catch(function(){alert('Falha ao gravar as confirmacoes. Tente salvar novamente.');return false}).then(function(ok){window.fmConfirmacaoPreEmAndamento=false;confirmacaoPreEmAndamento=false;estado.renderCompletoBloqueadoAte=0;renderPreLancamentos();return ok})}
function confirmarPre(id){if(confirmacaoPreEmAndamento)return Promise.resolve(false);confirmacaoPreEmAndamento=true;window.fmConfirmacaoPreEmAndamento=true;var r=aplicarConfirmacaoPre(id,false);if(!r.ok){confirmacaoPreEmAndamento=false;window.fmConfirmacaoPreEmAndamento=false;if(r.erro)alert(r.erro);renderPreLancamentos();return Promise.resolve(false)}return persistirConfirmacoes(1,0)}
function confirmarSelecionados(){if(confirmacaoPreEmAndamento)return;var todos=document.getElementById('cusPreTodos'),ids=todos&&todos.checked?preFiltrados().map(function(x){return x.id}):Array.from(document.querySelectorAll('.cus-pre-selecao:checked')).map(function(x){return x.value});ids=ids.filter(function(id,i){return id&&ids.indexOf(id)===i});if(!ids.length){alert('Selecione ao menos um pre-lancamento.');return}confirmacaoPreEmAndamento=true;window.fmConfirmacaoPreEmAndamento=true;var processados=0,correcoes=0,contexto=contextoConfirmacaoPre(),pos=0;function bloco(){try{var limite=Math.min(pos+20,ids.length);for(;pos<limite;pos++){var r=aplicarConfirmacaoPre(ids[pos],true,contexto);if(r.ok){if(!r.jaProcessado)processados++}else if(r.correcao)correcoes++}if(pos<ids.length){setTimeout(bloco,0);return}persistirConfirmacoes(processados,correcoes)}catch(e){console.error('Falha ao confirmar pre-lancamentos:',e);confirmacaoPreEmAndamento=false;window.fmConfirmacaoPreEmAndamento=false;estado.renderCompletoBloqueadoAte=0;alert('Ocorreu um erro ao confirmar os pre-lancamentos. Nenhum dado foi perdido: tente novamente.');renderPreLancamentos()}}setTimeout(bloco,0)}
function selecionarPre(marcar){document.querySelectorAll('.cus-pre-selecao').forEach(function(x){x.checked=!!marcar});var todos=document.getElementById('cusPreTodos');if(todos)todos.checked=!!marcar}
function descartarPre(id){if(!confirm('Descartar este pré-lançamento? O registro original será mantido.'))return;var x=arr('preLancamentos').find(function(y){return y.id===id});if(!x)return;x.situacaoPre='descartado';x.atualizadoEm=new Date().toISOString();(function(){window.fmPularSincronizacaoPreUmaVez=true;return salvarNuvem(['preLancamentos'])})();renderPreLancamentos()}
function renderPendencias(l,f,km){var el=document.getElementById('cusPendencias');if(!el)return;var msgs=[],blocos=[];if(!km)msgs.push('quilometragem ausente');
var semVeiculo=l.filter(function(x){return !x.veiculo&&x.rateio==='nao'});
if(semVeiculo.length){msgs.push(semVeiculo.length+' custo(s) sem veículo ou rateio');
blocos.push('<div class="cus-pend-bloco"><div class="cus-pend-tit">Custos sem veículo ou rateio</div>'+semVeiculo.map(function(x){var acao=x.id?'<button type="button" class="cus-pend-btn" onclick="editarCustoFrota(\''+esc(String(x.id))+'\')">Corrigir</button>':'<span class="cus-mini">'+esc(x.origemLabel||x.origem||'automático')+'</span>';return '<div class="cus-pend-item"><span>'+esc(data(x.data)||'sem data')+'</span><span>'+esc(x.categoria||'sem categoria')+'</span><span>'+esc(x.descricao||'')+'</span><strong>'+brl(num(x.valor))+'</strong>'+acao+'</div>'}).join('')+'</div>')}
var rec=arr('custosRecorrentes').filter(function(x){return x.periodicidade==='anual'&&!x.inicio});
if(rec.length){msgs.push(rec.length+' custo(s) anual(is) sem vigência');
blocos.push('<div class="cus-pend-bloco"><div class="cus-pend-tit">Custos anuais sem vigência</div>'+rec.map(function(x){var acao=x.id?'<button type="button" class="cus-pend-btn" onclick="editarCustoRecorrente(\''+esc(String(x.id))+'\')">Corrigir</button>':'';return '<div class="cus-pend-item"><span>'+esc(x.categoria||'sem categoria')+'</span><span>'+esc(x.veiculo||'sem veículo')+'</span><span>'+esc(x.descricao||'')+'</span><strong>'+brl(num(x.valor))+'</strong>'+acao+'</div>'}).join('')+'</div>')}
el.classList.toggle('show',!!msgs.length);
el.innerHTML=msgs.length?'<div class="cus-pend-msg">Pendências para um cálculo completo: '+esc(msgs.join(' • '))+'</div>'+blocos.join(''):''}
function tipoBadge(x){return x.tipo==='fixo'?'fix':x.tipo==='indireto'?'ind':'var'}
function paginar(lista,chave){var paginas=Math.max(1,Math.ceil(lista.length/estado.itensPagina));estado[chave]=Math.min(Math.max(1,estado[chave]||1),paginas);var ini=(estado[chave]-1)*estado.itensPagina,fn="mudarPaginaGestao('"+chave+"',";return {itens:lista.slice(ini,ini+estado.itensPagina),html:lista.length>estado.itensPagina?'<div class="paginacao-global"><button '+(estado[chave]===1?'disabled':'')+' onclick="'+fn+'1)">&lt;&lt; Primeira</button><button '+(estado[chave]===1?'disabled':'')+' onclick="'+fn+(estado[chave]-1)+')">&lt; Anterior</button><div class="pagina-info">Página '+estado[chave]+' de '+paginas+'</div><button '+(estado[chave]===paginas?'disabled':'')+' onclick="'+fn+(estado[chave]+1)+')">Próxima &gt;</button><button '+(estado[chave]===paginas?'disabled':'')+' onclick="'+fn+paginas+')">Última &gt;&gt;</button></div>':''}}
function renderTabela(l){var tb=document.getElementById('cusLista');if(!tb)return;var p=paginar(l,'paginaLancamentos');tb.innerHTML=p.itens.length?p.itens.map(function(x){var alvo=x.lancamentoId||x.id,acao=x.projecaoRecorrente?'<span class="cus-mini">projeção</span>':x.automatico?'<span class="cus-mini">automático</span>':'<button class="btn-edit" onclick="editarCustoFrota(\''+esc(alvo)+'\')">✎ Editar</button><button class="btn-del" onclick="excluirCustoFrota(\''+esc(alvo)+'\')">✕ Excluir</button>',parcela=x.parcelas>1?x.parcelaAtual+'/'+x.parcelas:'À vista';return '<tr><td>'+esc(x.data?x.data.split('-').reverse().join('/'):'--')+'</td><td>'+esc(x.competencia||'--')+'</td><td><b>'+esc(x.veiculo||'Frota geral')+'</b></td><td>'+esc(x.categoria)+'</td><td>'+esc(x.descricao||'--')+(x.rateado?'<span class="cus-source-note">valor rateado</span>':'')+'</td><td>'+esc(parcela)+'</td><td><span class="cus-badge '+tipoBadge(x)+'">'+(x.tipo==='fixo'?'Fixo':x.tipo==='indireto'?'Indireto':'Variável')+'</span></td><td><span class="cus-badge manual">'+esc(x.origem==='pedagio_importado'?'Pedágio mensal':x.origem)+'</span></td><td>'+esc(x.status||'Realizado')+'</td><td><b>'+brl(x.valor)+'</b>'+(x.parcelas>1?'<span class="cus-source-note">total '+brl(x.valorTotal)+'</span>':'')+'</td><td class="cus-history-actions">'+acao+'</td></tr>'}).join(''):'<tr><td colspan="11" class="cus-empty">Nenhum custo encontrado neste período.</td></tr>';var pg=document.getElementById('cusListaPaginacao');if(pg)pg.innerHTML=p.html}
function renderCategorias(l,total){var m={};l.forEach(function(x){m[x.categoria]=(m[x.categoria]||0)+x.valor});var el=document.getElementById('cusCategorias');if(!el)return;el.innerHTML=Object.keys(m).sort(function(a,b){return m[b]-m[a]}).slice(0,10).map(function(k){var p=total?m[k]/total*100:0;return '<div class="mb-3"><div class="d-flex justify-content-between"><b>'+esc(k)+'</b><span>'+brl(m[k])+' · '+p.toFixed(1).replace('.',',')+'%</span></div><div class="cus-progress"><i style="width:'+Math.min(100,p)+'%"></i></div></div>'}).join('')||'<div class="cus-empty">Sem dados no período.</div>'}
function renderVeiculos(f,base){var placas=f.v?[f.v]:veiculosGestao(),linhas=[];placas.forEach(function(pl){if(window.FMResultadoAPI){var r=window.FMResultadoAPI.resumo(pl,f,'competencia',base);var fat=faturamentoPeriodo(pl,f.ini,f.fim);if(r.c.total||r.km||fat||r.receita)linhas.push({placa:pl,faturamento:fat,receitaLiquida:r.receita,fix:r.c.fix,vari:r.c.vari,ind:r.c.ind,total:r.c.total,km:r.km});return}var l=filtrados(pl,f,base),fix=0,vari=0,ind=0;l.forEach(function(x){if(x.tipo==='fixo')fix+=x.valor;else if(x.tipo==='indireto')ind+=x.valor;else vari+=x.valor});var total=fix+vari+ind,km=kmPeriodo(pl,f.ini,f.fim),faturamento=faturamentoPeriodo(pl,f.ini,f.fim),receitaLiquida=receitaLiquidaPeriodo(pl,f.ini,f.fim);if(total||km||faturamento||receitaLiquida)linhas.push({placa:pl,faturamento:faturamento,receitaLiquida:receitaLiquida,fix:fix,vari:vari,ind:ind,total:total,km:km})});var el=document.getElementById('cusPorVeiculo'),p=paginar(linhas,'paginaVeiculos');if(el)el.innerHTML=p.itens.map(function(x){return '<tr><td><b>'+esc(x.placa)+'</b></td><td><b>'+brl(x.faturamento)+'</b></td><td><b>'+brl(x.receitaLiquida)+'</b></td><td>'+brl(x.fix)+'</td><td>'+brl(x.vari)+'</td><td>'+brl(x.ind)+'</td><td><b>'+brl(x.total)+'</b></td><td>'+x.km.toLocaleString('pt-BR')+' km</td><td><b>'+(x.km?brl(x.total/x.km):'--')+'</b></td></tr>'}).join('')||'<tr><td colspan="9" class="cus-empty">Sem dados por veículo.</td></tr>';var pg=document.getElementById('cusVeiculosPaginacao');if(pg)pg.innerHTML=p.html}
function grafico(l){var el=document.getElementById('cusGrafico');if(!el||typeof Chart==='undefined')return;var m={};l.forEach(function(x){m[x.categoria]=(m[x.categoria]||0)+x.valor});var ks=Object.keys(m).sort(function(a,b){return m[b]-m[a]}).slice(0,8);if(estado.chart)estado.chart.destroy();estado.chart=new Chart(el,{type:'doughnut',data:{labels:ks,datasets:[{data:ks.map(function(k){return m[k]}),backgroundColor:['#2563eb','#0f766e','#f59e0b','#dc2626','#7c3aed','#0891b2','#64748b','#db2777'],borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom'}}}})}
var CATS_FOLHA=['Salário','Encargos patronais','FGTS','Benefícios','13º salário','Férias + 1/3'];
function recAtivoNaCompetencia(r,comp){if(r.ativo===false)return false;var ini=data(r.inicio),fim=data(r.fim);if(ini&&ini.slice(0,7)>comp)return false;if(fim&&fim.slice(0,7)<comp)return false;return true}
function dentroVigencia(comp,ini,fim){if(!comp)return false;if(ini&&data(ini).slice(0,7)>comp)return false;if(fim&&data(fim).slice(0,7)<comp)return false;return true}
function preDuplicados(cat,veiculo,ini,fim){var p=normalizarPlaca(veiculo);return prePendentes().filter(function(x){return x.categoria===cat&&normalizarPlaca(x.veiculo)===p&&dentroVigencia((x.competencia||data(x.data).slice(0,7)),ini,fim)})}
function conferirDuplicidadeLancamento(cat,veiculo,comp,idEdicao){if(idEdicao)return true;var p=normalizarPlaca(veiculo),achado=arr('custosRecorrentes').filter(function(r){return r.categoria===cat&&normalizarPlaca(r.veiculo)===p&&recAtivoNaCompetencia(r,comp)});if(achado.length&&!confirm('Atenção: já existe um custo de "'+cat+'"'+(veiculo?' para '+veiculo:' para a frota geral')+' cadastrado em Fixos e pessoal, ativo na competência '+comp+'.\n\nEsse valor já entra sozinho na lista de Lançamentos como projeção. Salvar aqui vai contar o custo duas vezes.\n\nDeseja salvar mesmo assim?'))return false;var pre=preDuplicados(cat,veiculo,comp+'-01',comp+'-28');if(pre.length&&!confirm('Existe '+pre.length+' pré-lançamento(s) de "'+cat+'"'+(veiculo?' para '+veiculo:'')+' aguardando conferência na competência '+comp+'.\n\nSe você confirmar aquele pré-lançamento depois, o custo entra duas vezes.\n\nDeseja salvar mesmo assim?'))return false;return true}
function conferirDuplicidadeRecorrente(cat,veiculo,idEdicao){if(CATS_FOLHA.indexOf(cat)>=0&&!idEdicao){alert('"'+cat+'" faz parte da folha do motorista.\n\nUse o quadro "Folha do motorista": ele cria sozinho salário, encargos, FGTS, benefícios, 13º e férias. Lançar aqui duplicaria o custo.');return false}var p=normalizarPlaca(veiculo),ini=val('cusRecInicio')||mesInicio(),fim=val('cusRecFim'),achado=arr('custosRecorrentes').filter(function(r){return r.id!==idEdicao&&r.ativo!==false&&r.categoria===cat&&normalizarPlaca(r.veiculo)===p});if(achado.length&&!confirm('Já existe um custo de "'+cat+'"'+(veiculo?' para '+veiculo:' para a frota geral')+' nesta aba.\n\nCriar outro faz os dois somarem todo mês. O certo costuma ser editar o existente.\n\nDeseja continuar?'))return false;var manuais=arr('custos').filter(function(c){return c.categoria===cat&&normalizarPlaca(c.veiculo)===p&&dentroVigencia((c.competencia||data(c.data).slice(0,7)),ini,fim)});if(manuais.length&&!confirm('Já existe '+manuais.length+' lançamento(s) de "'+cat+'"'+(veiculo?' para '+veiculo:'')+' dentro dessa vigência na aba Lançamentos.\n\nComo este custo passa a entrar sozinho todo mês, o valor seria contado duas vezes.\n\nDeseja continuar mesmo assim?'))return false;var pre=preDuplicados(cat,veiculo,ini,fim);if(pre.length&&!confirm('Existe '+pre.length+' pré-lançamento(s) de "'+cat+'"'+(veiculo?' para '+veiculo:'')+' aguardando conferência dentro dessa vigência.\n\nSe forem confirmados, o custo entra duas vezes. O certo é descartá-los.\n\nDeseja continuar mesmo assim?'))return false;return true}
function conferirDuplicidadeFolha(veiculo,motorista){var p=normalizarPlaca(veiculo),m=String(motorista||'').trim().toUpperCase(),achado=arr('custosRecorrentes').filter(function(r){return r.origem==='pessoal'&&r.ativo!==false&&normalizarPlaca(r.veiculo)===p&&String(r.motorista||'').trim().toUpperCase()===m});if(!achado.length)return true;return confirm('Já existe folha cadastrada para '+motorista+' em '+veiculo+'.\n\nSalvar de novo vai duplicar salário, encargos e benefícios todo mês. O certo é editar ou excluir a folha atual na lista abaixo.\n\nDeseja continuar?')}
function atualizarAposCorrecaoCusto(){var f=filtros(),base=todosBase(),lista=filtrados(undefined,f,base).filter(function(x){return f.v||!x.veiculo||!veiculoVendido(x.veiculo)});renderTabela(lista);renderPendencias(lista,f,kmPeriodo(f.v,f.ini,f.fim))}
function salvarCusto(){if(window.fmSalvandoCorrecaoCusto)return Promise.resolve(false);var id=val('cusIdx'),cat=val('cusCategoria'),valor=num(val('cusValor')),dt=val('cusData'),veiculo=val('cusVeiculo'),parcelado=val('cusPagamento')==='parcelado',parcelas=parcelado?Math.floor(num(val('cusParcelas'))):1;if(!dt||!cat||valor<=0){alert('Informe data, categoria e um valor maior que zero.');return false}if(parcelado&&(parcelas<2||parcelas>120)){alert('Informe entre 2 e 120 parcelas.');return false}if(!validarVeiculoNovo(veiculo,id))return false;if(!conferirDuplicidadeLancamento(cat,veiculo,val('cusCompetencia')||dt.slice(0,7),id))return false;var idx=arr('custos').findIndex(function(x){return x.id===id}),anterior=idx>=0?arr('custos')[idx]:null,obj=Object.assign({},anterior||{},{id:id||uid('cus'),data:dt,competencia:val('cusCompetencia')||dt.slice(0,7),veiculo:veiculo,motorista:val('cusMotorista'),categoria:cat,tipo:val('cusTipo')||CATS[cat]||'variavel',descricao:val('cusDescricao'),valor:valor,parcelas:parcelas,status:val('cusStatus'),rateio:val('cusRateio'),observacao:val('cusObservacao'),origem:anterior&&anterior.origem?anterior.origem:'manual',atualizadoEm:new Date().toISOString()});if(idx<0)arr('custos').push(obj);else db.custos[idx]=obj;limparCusto();atualizarAposCorrecaoCusto();if(idx>=0&&typeof window.fmSalvarCorrecaoCusto==='function')return window.fmSalvarCorrecaoCusto(obj);window.fmFilaSemCopiaDadosUmaVez=true;return Promise.resolve(salvarNuvem(['custos']))}
function editarCusto(id){var x=arr('custos').find(function(y){return y.id===id});if(!x)return;var map={Data:'data',Competencia:'competencia',Veiculo:'veiculo',Motorista:'motorista',Categoria:'categoria',Tipo:'tipo',Descricao:'descricao',Status:'status',Rateio:'rateio',Observacao:'observacao'};Object.keys(map).forEach(function(s){var e=document.getElementById('cus'+s);if(e)e.value=x[map[s]]||''});var campoValor=document.getElementById('cusValor');if(campoValor)campoValor.value=brl(num(x.valor));document.getElementById('cusIdx').value=x.id;marcarModoEdicaoCusto(x);document.getElementById('cusPagamento').value=num(x.parcelas)>1?'parcelado':'avista';document.getElementById('cusParcelas').value=Math.max(2,Math.floor(num(x.parcelas)||2));alternarParcelamento();trocarAba('lancamentos');document.getElementById('cusData').scrollIntoView({behavior:'smooth',block:'center'})}
function excluirCusto(id){if(!confirm('Excluir este lançamento?'))return;var i=arr('custos').findIndex(function(x){return x.id===id});if(i<0)return;db.custos.splice(i,1);salvarNuvem(['custos']);render()}
function alternarParcelamento(){var parcelado=val('cusPagamento')==='parcelado',grupo=document.getElementById('cusParcelasGrupo'),campo=document.getElementById('cusParcelas');if(grupo)grupo.classList.toggle('hidden',!parcelado);if(campo){campo.disabled=!parcelado;if(parcelado&&num(campo.value)<2)campo.value='2'}}
function marcarModoEdicaoCusto(x){var t=document.getElementById('cusFormTitulo'),a=document.getElementById('cusFormAviso');if(!t||!a)return;if(!x){t.textContent='Novo lançamento';a.classList.add('hidden');a.textContent='';return}t.textContent='Corrigindo lançamento já salvo';a.classList.remove('hidden');a.textContent='Este lançamento já está salvo'+(x.origem==='integrado'?' (confirmado a partir de '+(x.origemNome||'outro módulo')+')':'')+'. Você está apenas editando os dados abaixo — ele não voltou para os pré-lançamentos. Use Cancelar para sair sem alterar.'}
function limparCusto(){['cusIdx','cusData','cusCompetencia','cusVeiculo','cusMotorista','cusCategoria','cusDescricao','cusValor','cusObservacao'].forEach(function(id){var e=document.getElementById(id);if(e)e.value=''});document.getElementById('cusTipo').value='variavel';document.getElementById('cusPagamento').value='avista';document.getElementById('cusParcelas').value='2';document.getElementById('cusStatus').value='Realizado';document.getElementById('cusRateio').value='nao';marcarModoEdicaoCusto(null);alternarParcelamento()}
function salvarRec(){var xid=val('cusRecIdx'),cat=val('cusRecCategoria'),valor=num(val('cusRecValor')),per=val('cusRecPeriodicidade')||'mensal',veiculo=val('cusRecVeiculo');if(!cat||valor<=0){alert('Informe categoria e valor.');return}if(!validarVeiculoNovo(veiculo,xid))return;if(!conferirDuplicidadeRecorrente(cat,veiculo,xid))return;var obj={id:xid||uid('rec'),categoria:cat,tipo:val('cusRecTipo')||CATS[cat]||'fixo',veiculo:veiculo,motorista:val('cusRecMotorista'),descricao:val('cusRecDescricao'),valor:valor,periodicidade:per,inicio:val('cusRecInicio')||mesInicio(),fim:val('cusRecFim'),rateio:val('cusRecRateio')||'nao',ativo:true,atualizadoEm:new Date().toISOString()},ix=arr('custosRecorrentes').findIndex(function(x){return x.id===obj.id});if(ix<0)arr('custosRecorrentes').push(obj);else db.custosRecorrentes[ix]=obj;salvarNuvem(['custosRecorrentes']);cancelarRec();render()}
function totalFolha(){var salario=num(val('cusPesSalario'));return salario+salario*num(val('cusPesEncargos'))/100+salario*num(val('cusPesFgts'))/100+num(val('cusPesBeneficios'))+salario/12+salario/9}
function atualizarTotalFolha(){set('cusPesTotal',brl(totalFolha()))}
function salvarPessoal(){var salario=num(val('cusPesSalario')),veiculo=val('cusPesVeiculo'),motorista=val('cusPesMotorista'),inicio=val('cusPesInicio')||mesInicio();if(!veiculo||!motorista||salario<=0){alert('Informe veículo, motorista e salário-base.');return}if(!validarVeiculoNovo(veiculo,''))return;if(!conferirDuplicidadeFolha(veiculo,motorista))return;var grupo=uid('folha'),itens=[['Salário',salario],['Encargos patronais',salario*num(val('cusPesEncargos'))/100],['FGTS',salario*num(val('cusPesFgts'))/100],['Benefícios',num(val('cusPesBeneficios'))],['13º salário',salario/12],['Férias + 1/3',salario/9]];itens.forEach(function(it){if(it[1]<=0)return;arr('custosRecorrentes').push({id:uid('pes'),grupoId:grupo,origem:'pessoal',categoria:it[0],tipo:'fixo',veiculo:veiculo,motorista:motorista,descricao:it[0]+' — '+motorista,valor:it[1],periodicidade:'mensal',inicio:inicio,rateio:'nao',ativo:true})});salvarNuvem(['custosRecorrentes']);['cusPesVeiculo','cusPesMotorista','cusPesSalario','cusPesEncargos','cusPesFgts','cusPesBeneficios','cusPesInicio'].forEach(function(id){var e=document.getElementById(id);if(e)e.value=''});atualizarTotalFolha();render()}
function renderRecorrentes(){var el=document.getElementById('cusRecLista');if(!el)return;var f=filtros(),lista=arr('custosRecorrentes').filter(function(x){var origem=x.origem||'recorrente',ini=data(x.inicio),fim=data(x.fim);return x.ativo!==false&&(!f.v||normalizarPlaca(x.veiculo)===normalizarPlaca(f.v))&&(!f.tipo||x.tipo===f.tipo)&&(!f.cat||x.categoria===f.cat)&&(!f.origem||origem===f.origem)&&(!ini||ini<=data(f.fim))&&(!fim||fim>=data(f.ini))}),p=paginar(lista,'paginaRecorrentes');el.innerHTML=p.itens.map(function(x){var mensal=x.periodicidade==='anual'?num(x.valor)/12:num(x.valor);return '<div class="cus-rec-row"><div><b>'+esc(x.descricao||x.categoria)+'</b><div class="cus-mini">'+esc(x.categoria)+' · '+esc(x.veiculo||'Frota geral')+(x.motorista?' · '+esc(x.motorista):'')+'</div></div><span>'+brl(mensal)+'/mês</span><span>'+(x.periodicidade==='anual'?brl(num(x.valor))+' anual':'Mensal')+'</span><span>'+esc(x.inicio||'--')+'</span><span class="cus-history-actions"><button class="btn-edit" onclick="editarCustoRecorrente(\''+esc(x.id)+'\')">✎ Editar</button><button class="btn-del" onclick="excluirCustoRecorrente(\''+esc(x.id)+'\')">✕ Excluir</button></span></div>'}).join('')||'<div class="cus-empty">Nenhum custo fixo ou de pessoal com os filtros selecionados.</div>';var pg=document.getElementById('cusRecPaginacao');if(pg)pg.innerHTML=p.html}
function editarRec(id){var x=arr('custosRecorrentes').find(function(y){return y.id===id});if(!x)return;var map={Idx:'id',Categoria:'categoria',Tipo:'tipo',Periodicidade:'periodicidade',Valor:'valor',Veiculo:'veiculo',Motorista:'motorista',Descricao:'descricao',Inicio:'inicio',Fim:'fim',Rateio:'rateio'};Object.keys(map).forEach(function(k){var e=document.getElementById('cusRec'+k);if(e)e.value=x[map[k]]||''});trocarAba('recorrentes')}
function cancelarRec(){['cusRecIdx','cusRecDescricao','cusRecValor','cusRecFim','cusRecVeiculo','cusRecMotorista'].forEach(function(id){var e=document.getElementById(id);if(e)e.value=''});var i=document.getElementById('cusRecInicio');if(i)i.value=mesInicio()}
function excluirRec(id){if(!confirm('Excluir este custo e suas provisões relacionadas?'))return;var alvo=arr('custosRecorrentes').find(function(x){return x.id===id}),grupo=alvo&&alvo.grupoId;db.custosRecorrentes=arr('custosRecorrentes').filter(function(x){return grupo?x.grupoId!==grupo:x.id!==id});salvarNuvem(['custosRecorrentes']);render()}
function ultimoOdometro(veiculo,idIgnorado){var placa=normalizarPlaca(veiculo),lista=arr('quilometragens').filter(function(x){return x.id!==idIgnorado&&normalizarPlaca(x.veiculo)===placa&&num(x.odometroFinal)>0}).sort(function(a,b){return (data(b.data)+'|'+String(b.atualizadoEm||'')).localeCompare(data(a.data)+'|'+String(a.atualizadoEm||''))});return lista.length?num(lista[0].odometroFinal):0}
function veiculoCadastro(placa){var p=normalizarPlaca(placa);return arr('veiculos').find(function(v){return normalizarPlaca(v.vplaca)===p})}
function atualizarOdometroInicial(){var xid=val('cusKmIdx'),iniEl=document.getElementById('cusKmInicial'),fimEl=document.getElementById('cusKmFinal'),dataEl=document.getElementById('cusKmData');if(!iniEl||!fimEl)return;var veic=veiculoCadastro(val('cusKmVeiculo')),ultimo=ultimoOdometro(val('cusKmVeiculo'),xid),inicial=ultimo||(veic?num(veic.vkminicial):0),atual=veic?num(veic.vkm):0;iniEl.value=inicial||'';fimEl.value=atual&&atual>=num(iniEl.value)?String(atual):'';if(dataEl&&!dataEl.value)dataEl.value=hoje();calcularKm('final')}
function calcularKm(origem){var iniEl=document.getElementById('cusKmInicial'),fimEl=document.getElementById('cusKmFinal'),kmEl=document.getElementById('cusKmRodado');if(!iniEl||!fimEl||!kmEl)return;var ini=num(iniEl.value),fim=num(fimEl.value),km=num(kmEl.value);if(origem==='rodado'){fimEl.value=iniEl.value!==''&&kmEl.value!==''?String(ini+km):'';return}if(iniEl.value!==''&&fimEl.value!==''&&fim>=ini){kmEl.value=String(fim-ini)}else if(origem==='inicial'&&iniEl.value!==''&&kmEl.value!==''){fimEl.value=String(ini+km)}else if(fim<ini){kmEl.value=''}}
function salvarKm(){var xid=val('cusKmIdx'),v=val('cusKmVeiculo'),d=val('cusKmData'),ini=num(val('cusKmInicial')),fim=num(val('cusKmFinal')),km=fim-ini;if(!v||!d||val('cusKmInicial')===''||val('cusKmFinal')===''||km<=0||fim<ini){alert('Confira veículo, data e odômetros. O odômetro final deve ser maior que o inicial.');return}if(!validarVeiculoNovo(v,xid))return;var obj={id:xid||uid('km'),veiculo:v,data:d,kmRodado:km,odometroInicial:ini,odometroFinal:fim,observacao:val('cusKmObs'),confirmado:true,atualizadoEm:new Date().toISOString()},ix=arr('quilometragens').findIndex(function(x){return x.id===obj.id});if(ix<0)arr('quilometragens').push(obj);else db.quilometragens[ix]=obj;var veic=veiculoCadastro(v);var mods=['quilometragens'];if(veic&&fim>num(veic.vkm)){veic.vkm=fim;mods.push('veiculos')}salvarNuvem(mods);cancelarKm();render()}
function renderKm(){var el=document.getElementById('cusKmLista');if(!el)return;var f=filtros(),lista=arr('quilometragens').filter(function(x){var dt=data(x.data);return (!f.v||normalizarPlaca(x.veiculo)===normalizarPlaca(f.v))&&(!f.ini||dt>=data(f.ini))&&(!f.fim||dt<=data(f.fim))}).slice().sort(function(a,b){return data(b.data).localeCompare(data(a.data))}),p=paginar(lista,'paginaKm');el.innerHTML=p.itens.map(function(x){return '<tr><td>'+esc(data(x.data).split('-').reverse().join('/'))+'</td><td><b>'+esc(x.veiculo)+'</b></td><td>'+num(x.kmRodado).toLocaleString('pt-BR')+' km</td><td>'+num(x.odometroInicial).toLocaleString('pt-BR')+'</td><td>'+num(x.odometroFinal).toLocaleString('pt-BR')+'</td><td>'+esc(x.observacao||'--')+'</td><td class="cus-history-actions"><button class="btn-edit" onclick="editarQuilometragem(\''+esc(x.id)+'\')">✎ Editar</button><button class="btn-del" onclick="excluirQuilometragem(\''+esc(x.id)+'\')">✕ Excluir</button></td></tr>'}).join('')||'<tr><td colspan="7" class="cus-empty">Nenhuma quilometragem com os filtros selecionados.</td></tr>';var pg=document.getElementById('cusKmPaginacao');if(pg)pg.innerHTML=p.html}
function editarKm(id){var x=arr('quilometragens').find(function(y){return y.id===id});if(!x)return;var map={Idx:'id',Veiculo:'veiculo',Data:'data',Rodado:'kmRodado',Inicial:'odometroInicial',Final:'odometroFinal',Obs:'observacao'};Object.keys(map).forEach(function(k){var e=document.getElementById('cusKm'+k);if(e)e.value=x[map[k]]||''});trocarAba('quilometragem')}
function cancelarKm(){['cusKmIdx','cusKmVeiculo','cusKmRodado','cusKmInicial','cusKmFinal','cusKmObs'].forEach(function(id){var e=document.getElementById(id);if(e)e.value=''});var d=document.getElementById('cusKmData');if(d)d.value=hoje()}
function excluirKm(id){if(!confirm('Excluir esta quilometragem?'))return;db.quilometragens=arr('quilometragens').filter(function(x){return x.id!==id});salvarNuvem(['quilometragens']);render()}
function reiniciarPaginasFiltros(){['paginaLancamentos','paginaPreLancamentos','paginaRecorrentes','paginaKm','paginaVeiculos'].forEach(function(k){estado[k]=1});if(typeof window.reiniciarPaginasResultadoFrota==='function')window.reiniciarPaginasResultadoFrota()}
function periodo(tipo){var d=new Date(),ini,fim;if(tipo==='mes'){ini=new Date(d.getFullYear(),d.getMonth(),1);fim=new Date(d.getFullYear(),d.getMonth()+1,0)}else if(tipo==='anterior'){ini=new Date(d.getFullYear(),d.getMonth()-1,1);fim=new Date(d.getFullYear(),d.getMonth(),0)}else if(tipo==='tri'){ini=new Date(d.getFullYear(),d.getMonth()-2,1);fim=new Date(d.getFullYear(),d.getMonth()+1,0)}else{ini=new Date(d.getFullYear(),0,1);fim=new Date(d.getFullYear(),11,31)}document.getElementById('cusFiltroInicio').value=ini.getFullYear()+'-'+String(ini.getMonth()+1).padStart(2,'0')+'-'+String(ini.getDate()).padStart(2,'0');document.getElementById('cusFiltroFim').value=fim.getFullYear()+'-'+String(fim.getMonth()+1).padStart(2,'0')+'-'+String(fim.getDate()).padStart(2,'0');reiniciarPaginasFiltros();render()}
function limparFiltros(){['cusFiltroVeiculo','cusFiltroInicio','cusFiltroFim','cusFiltroTipo','cusFiltroCategoria','cusFiltroOrigem','cusFiltroStatus'].forEach(function(id){var e=document.getElementById(id);if(e)e.value=''});reiniciarPaginasFiltros();render()}
function trocarAba(nome){estado.tab=nome;document.querySelectorAll('.cus-tab').forEach(function(e){e.classList.toggle('active',e.dataset.tab===nome)});document.querySelectorAll('.cus-pane').forEach(function(e){e.classList.toggle('hidden',e.id!=='cusPane-'+nome)});render()}
function exportar(){var f=filtros(),l=filtrados(),det=l.map(function(x){return {'Data':x.data,'Competência':x.competencia,'Veículo':x.veiculo||'Frota geral','Motorista':x.motorista||'','Categoria':x.categoria,'Tipo':x.tipo,'Descrição':x.descricao,'Parcela':x.parcelas>1?x.parcelaAtual+'/'+x.parcelas:'À vista','Valor total (R$)':x.valorTotal||x.valor,'Origem':x.origem,'Situação':x.status,'Valor mensal (R$)':x.valor}});if(!det.length){alert('Não há dados para exportar.');return}var wb=XLSX.utils.book_new(),ws=XLSX.utils.json_to_sheet(det),placas=f.v?[f.v]:veiculosGestao(),res=[];placas.forEach(function(p){var itens=filtrados(p),t=itens.reduce(function(s,x){return s+x.valor},0),km=kmPeriodo(p,f.ini,f.fim),fat=faturamentoPeriodo(p,f.ini,f.fim),liq=receitaLiquidaPeriodo(p,f.ini,f.fim);if(t||km||fat||liq)res.push({'Veículo':p,'Faturamento total (R$)':fat,'Receita líquida (R$)':liq,'Custo total (R$)':t,'KM':km,'Custo por KM (R$)':km?t/km:0})});XLSX.utils.book_append_sheet(wb,ws,'Lançamentos manuais');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(res),'Resumo por veículo');XLSX.writeFile(wb,'FrotaMaster_Gestao_Frota_'+hoje()+'.xlsx')}
function veiculosGestao(){var m={},vendidos={};arr('veiculos').forEach(function(v){if(!v.vplaca)return;if(veiculoVendido(v.vplaca))vendidos[normalizarPlaca(v.vplaca)]=true;else m[v.vplaca]=true});['custos','custosRecorrentes','quilometragens','producoes','gestaoDepreciacoes'].forEach(function(k){arr(k).forEach(function(x){if(x.veiculo&&!vendidos[normalizarPlaca(x.veiculo)])m[x.veiculo]=true})});return Object.keys(m).sort()}
function categoriaChange(prefix){var cat=val(prefix+'Categoria'),e=document.getElementById(prefix+'Tipo');if(e&&CATS[cat])e.value=CATS[cat]}
 function init(){var root=document.getElementById('custos');if(!root)return;migrarIds();sincronizarPreLancamentos();var cats='<option value="">Todas as categorias</option>'+Object.keys(CATS).map(function(k){return '<option value="'+esc(k)+'">'+esc(k)+'</option>'}).join('');document.getElementById('cusFiltroCategoria').innerHTML=cats;['cusCategoria','cusRecCategoria'].forEach(function(id){document.getElementById(id).innerHTML=cats.replace('<option value="">Todas as categorias</option>','<option value="">Selecione...</option>')});document.getElementById('cusFiltroInicio').value=mesInicio();document.getElementById('cusFiltroFim').value=mesFim();document.getElementById('cusData').value=hoje();document.getElementById('cusCompetencia').value=hoje().slice(0,7);document.getElementById('cusRecInicio').value=mesInicio();document.getElementById('cusPesInicio').value=mesInicio();document.getElementById('cusKmData').value=hoje();['cusPesSalario','cusPesEncargos','cusPesFgts','cusPesBeneficios'].forEach(function(id){var el=document.getElementById(id);if(el)el.addEventListener('input',atualizarTotalFolha)});alternarParcelamento();atualizarTotalFolha();render()}
var prev=window.renderModulo;window.renderModulo=function(mod){if(mod==='custos'){if(Date.now()<(estado.renderCompletoBloqueadoAte||0)){renderPreLancamentos();return}render();return}return typeof prev==='function'?prev.apply(this,arguments):undefined};
 window.mudarPaginaGestao=function(chave,p){estado[chave]=p;render()};window.fmSincronizarPreLancamentos=sincronizarPreLancamentos;window.editarPreLancamento=editarPre;window.confirmarPreLancamento=confirmarPre;window.confirmarPreLancamentosSelecionados=confirmarSelecionados;window.selecionarPreLancamentos=selecionarPre;window.descartarPreLancamento=descartarPre;window.FMCustosAPI={filtrados:filtrados,filtros:filtros,kmPeriodo:kmPeriodo,todosBase:todosBase,brl:brl,num:num,veiculos:veiculosGestao};window.renderCustosFrota=render;window.filtrarCustosFrota=function(){reiniciarPaginasFiltros();render()};window.limparFiltrosCustos=limparFiltros;window.salvarCustoFrota=salvarCusto;window.editarCustoFrota=editarCusto;window.excluirCustoFrota=excluirCusto;window.limparCustoFrota=limparCusto;window.alternarParcelamentoFrota=alternarParcelamento;window.salvarCustoRecorrente=salvarRec;window.editarCustoRecorrente=editarRec;window.cancelarCustoRecorrente=cancelarRec;window.salvarCustoPessoal=salvarPessoal;window.atualizarTotalFolha=atualizarTotalFolha;window.cancelarCustoPessoal=function(){['cusPesVeiculo','cusPesMotorista','cusPesSalario','cusPesEncargos','cusPesFgts','cusPesBeneficios'].forEach(function(id){var e=document.getElementById(id);if(e)e.value=''});atualizarTotalFolha()};window.excluirCustoRecorrente=excluirRec;window.salvarQuilometragem=salvarKm;window.editarQuilometragem=editarKm;window.cancelarQuilometragem=cancelarKm;window.excluirQuilometragem=excluirKm;window.atualizarOdometroInicial=atualizarOdometroInicial;window.calcularQuilometragem=calcularKm;window.aplicarPeriodoCustos=periodo;window.trocarAbaCustos=trocarAba;window.exportarCustosFrota=exportar;window.custoCategoriaChange=categoriaChange;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
